### ISSUE TITLE
`ActiveRecordEnum` compiler doesn't generate scopes

### ISSUE THREAD

**Issue by georgebrock** [Shopify/tapioca#1081]
From the [Rails docs](https://api.rubyonrails.org/classes/ActiveRecord/Enum.html):

> Declare an enum attribute where the values map to integers in the database, but can be queried by name. Example:
>
> ``` ruby
> class Conversation < ActiveRecord::Base
>   enum :status, [ :active, :archived ]
> end
>
> # …
> ```
>
> Scopes based on the allowed values of the enum field will be provided as well. With the above example:
>
> ``` ruby
> Conversation.active
> Conversation.not_active
> Conversation.archived
> Conversation.not_archived
> ```

The RBI files generated by the `ActiveRecordEnum` compiler don't include these methods.

The `ActiveRecordScope` compiler generates types for hand-written scopes, so whatever types are generated for these enum scopes should probably agree with those.

**Comment by paracycle** [comment]
I was able to take a look at this just now and the scope definitions are being properly generated, just not by the compiler that you expect it to come from. `ActiveRecordEnum` compiler is only responsible for discovering and generating the model methods that are added by the enum attribute, whereas `ActiveRecordScope` compiler is responsible for doing that for all scope definitions.

As the test I added in #1209 shows, the scopes related to enum attributes are being properly generated by the `ActiveRecordScope` compiler.
