### ISSUE TITLE
"Redefining constant" issue when generating dsl/rbi files for Protobuf

### ISSUE THREAD

**Issue by gaborszakacs** [Shopify/tapioca#1090]
I have a generated Ruby file from a protobuf3 definition like this (shortened for simplicity):

```ruby
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("build_archive/v1beta1/build_archive.proto", :syntax => :proto3) do
    add_message "build_archive.v1beta1.GetBuildRequest" do
      optional :app_id, :string, 1, json_name: "appId"
      optional :build_id, :string, 2, json_name: "buildId"
    end
  end
end

module RPC
  module BuildArchive
    module V1beta1
      GetBuildRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("build_archive.v1beta1.GetBuildRequest").msgclass
    end
  end
end
```

Tapioca Protubuf DSL generates an `rbi` file like this:

```ruby
class RPC::BuildArchive::V1beta1::GetBuildRequest
  sig { params(app_id: String, build_id: String).void }
  def initialize(app_id: nil, build_id: nil); end

  sig { returns(String) }
  def app_id; end

  sig { params(value: String).returns(String) }
  def app_id=(value); end

  sig { returns(String) }
  def build_id; end

  sig { params(value: String).returns(String) }
  def build_id=(value); end
end
```

This results in the following issue ([Sorbet error reference](https://sorbet.org/docs/error-reference#4012))

>  [sorbet 4012] [E] Redefining constant `RPC::BuildArchive::V1beta1::GetBuildRequest`

Should I generate my Protobuf files differently? 🤔 Is there a recommended way to resolve this?

**Comment by georgebrock** [comment]
The way I've been handling this is to ignore generated protobuf files in my Sorbet config file (e.g. adding lines like `--ignore=/lib/foo/foo_pb.rb`).

It seems reasonable to ignore them since the generated RBI files contain a complete definition of the interface, and the `*_pb.rb` file doesn't contain anything that's useful to Sorbet.

The Tapioca maintainers might have a better answer though.

**Comment by gaborszakacs** [comment]
Ahh, it didn't occur to me that I can simple do that 💡 It works as expected, thanks a lot!

It seems to be an easy fix, not sure if we have to come up with anything else, I've proposed a change to reflect this workaround in the Protobuf DSL manual though (see linked PR ⬆️ )
