### ISSUE TITLE
`bin/tapioca gem --verify` significantly slower on 0.9.x (vs 0.8.3)

### ISSUE THREAD

**Issue by pjambet** [Shopify/tapioca#1107]
We recently updated tapioca from 0.8.3 to 0.9.2 and it looks like the `bin/tapioca gem --verify` command we run on CI is now about 2x slower.

It seems like it used to usually take under 2 mins to run in CI, and it now regularly takes more than 4 mins.

Let me if there's more information I can share.

**Comment by rafaelfranca** [comment]
@pjambet if you can help you, can you try to narrow down to just one single release of tapioca. For example, is 0.9.1 also as slow as 0.9.2? That way we can find which release introduced the slowdown.

**Comment by pjambet** [comment]
@rafaelfranca I'll give this a shot this afternoon and update with my findings.

**Comment by pjambet** [comment]
@rafaelfranca I tried 0.9.0 & 0.9.1 and both show similar times as 0.9.2 (4m31s & 4m44s respectively). Also ran a control run on 0.8.3 one more time, and it ran in 2m4s. So it does seem to point at [0.9.0](https://github.com/Shopify/tapioca/compare/v0.8.3...v0.9.0) as the version introducing the slowdown.

**Comment by pjambet** [comment]
Just ran a similar test on the most two recent versions, 0.9.3 & 0.9.4 and saw similar "slow" types as observed since 0.9.0, respectively 5m20s and 6m46s

**Comment by pjambet** [comment]
@dirceu Just finished running a few builds on 0.10.0, 0.10.1 & 0.10.2 and got times that seem to match what we we observing on 0.8.x on the latest version, respectively, 6m50s, 5m56s & 2m15s (actually ran it three times on 0.10.2 and got 2m32s & 2m25s)

So it does look that 0.10.2 solved our issues!
