### ISSUE TITLE
Fix mixes_in_class_methods discovery

### ISSUE THREAD

**Issue by paracycle** [Shopify/tapioca#111]
The current implementation does not always produce the correct output. 

For example, instead of:
```ruby
mixes_in_class_methods(::ActiveModel::Validations::ClassMethods)
```
we produce:
```ruby
mixes_in_class_methods(::ActiveModel::Validations::HelperMethods)
```
in `module ActiveModel::Validations` which breaks type-checking.

We need to fix this and come up with a better way of implementing this feature.

**Comment by katayounHillier** [comment]
@ufuk ,what type_chaecking error are we getting for this issue ? i I am trying to understand as why we need to make this change, also I need to duplicate the error.
