### ISSUE TITLE
No platform for tzinfo-data breaks generating RBI for gems.

### ISSUE THREAD

**Issue by igbanam** [Shopify/tapioca#1123]
I'm trying to adopt Sorbet in a new Rails project. While trying to generate RBI files for the gems, I realize tapioca has some issues dealing with the `tzinfo-data` gem because the `@platform` is missing.

```
|| Removing RBI files of gems that have been removed:
|| /path/to/ruby-3.0.3/gems/bundler-2.3.19/lib/bundler/index.rb:84:in `block in sort_specs': undefined method `version' for #<Bundler::IncompleteSpecification:0x0000000123b61a38 @name="tzinfo-data", @platform=nil> (NoMethodError)
```

`tzinfo-data` is specified as its defaults

```
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
```

My current workaround is to

- re-bundle the gems after commenting out `tzinfo-data`
- run `tapioca gem [gem_name]`, then
- bring back `tzinfo-data`

OS X Version: 12.5
Ruby Version: 3.0.3

**Comment by wildmaples** [comment]
Thank you for the issue @igbanam - I was able to reproduce the bug you are describing: 

```
/Users/mapleong/.gem/ruby/3.1.1/gems/bundler-2.3.20/lib/bundler/index.rb:84:in `block in sort_specs': undefined method `version' for #<Bundler::IncompleteSpecification:0x0000000106e28f18 @name="tzinfo-data", @platform=nil> (NoMethodError)

        [s.version, platform_string == RUBY ? NULL : platform_string]
          ^^^^^^^^
	from /Users/mapleong/.gem/ruby/3.1.1/gems/bundler-2.3.20/lib/bundler/index.rb:82:in `each'
	from /Users/mapleong/.gem/ruby/3.1.1/gems/bundler-2.3.20/lib/bundler/index.rb:82:in `sort_by'
...
```

It seems like the `s.version` was nil. I did some digging to find that it was a bug in `bundler` that has been reported in this issue: https://github.com/rubygems/rubygems/issues/5849

And there was also a patch: https://github.com/rubygems/rubygems/pull/5840

To fix your immediate issue, you can either downgrade your Bundler version temporarily, or wait for the next release of Bundler.
