### ISSUE TITLE
Failure to run on Ruby 2.3.7 due to sorbet-runtime

### ISSUE THREAD

**Issue by texpert** [Shopify/tapioca#113]
After including Tapioca into the Gemfile and `bundle install`, trying to run it - fails:

```
00:58 $ bundle exec tapioca
/Users/thunder/.rvm/gems/ruby-2.3.7gems/sorbet-runtime-0.5.5878/lib/types/props/decorator.rb:246:in `validate_prop_name': undefined method `match?' for :outdir:Symbol (NoMethodError)
```

This was introduced in [this commit in sorbet-runtime](https://github.com/sorbet/sorbet/commit/68c732ed4479d762859e074950fbbc488cfaa4f4#diff-296495687573a8a72557282b673db5f5R243), and there is [a Sorbet issue opened](https://github.com/sorbet/sorbet/issues/2556).

Seems Ruby 2.3 will be removed from supported versions list.

**Comment by paracycle** [comment]
Yeah, sorry about that. We'd [dropped support for 2.3 a while back](https://github.com/Shopify/tapioca/commit/c73d5f0529929e59543edb82ef4eb0f129f64e51) but it seems we forgot to update the gemspec file to reflect that. I'll do that now.

In the absence of `sorbet-runtime` getting proper 2.3 support, we can't guarantee 2.3 support in this library either, I am afraid.
