### ISSUE TITLE
Migration Guide / Moving from `srb rbi gems`

### ISSUE THREAD

**Issue by coreyja** [Shopify/tapioca#114]
Hey everyone!

First off thanks so much for an awesome tool! It seems like a really great tool for the Sorbet ecosystem.

I'm trying to move some Rails apps over to Tapioca that were previously setup with `srb rbi gems`. Here was my approach for both these projects and the hiccups I ran into. If this is the correct migration guide for the most part I would be more than happy to help in committing it back to the docs!

Steps:
- Get a clean start for gem RBI `rm -rf sorbet/rbi/gems`
- Add tapioca to the Gemfile
- `tapioca init`
- Fix require file
- `tapioca sync`
- `srb rbi hidden-definitions` -- I am not sure about this step
- `tapioca todo`

After this I am in a pretty decent spot. I have a few issues that look like real things Tapioca helped catch. But I do have a few gem related type issues, and some places where the `sorbet-typed` definitions conflict with the `tapioca` gened RBIs.
In an effort to resolve those conflicts I ran `srb rbi sorbet-typed` and pulled in the latest rbis from there, which led to MORE conflicts between the `sorbet-typed` types and the auto-generated ones.

Specific Questions:
- Is Tapioca supposed to be used in conjunction with `srb rbi hidden-definitions`?
- Is Tapioca supposed to be used in conjunction with `srb rbi sorbet-typed`?

I notice that BOTH of those are not included in this repos rbi files, but would love some guidance on the expected workflow here! I can't tell if they are not included here cause they are not needed in this use case or cause they aren't part of the intended workflow

Thanks again everyone!

**Comment by coreyja** [comment]
One bit of guidance I received here is that Tapioca is NOT compatible with `sorbet-typed` which explains the issues I was running into where they conflicted.

Next time I attempt this I will also remove the `sorbet-typed` RBI files which I think will resolve at least some of this issues I faced!

**Comment by connorshea** [comment]
@coreyja do you use sorbet-rails with this or no?

**Comment by connorshea** [comment]
Also I think this is missing the `bundle exec tapioca require` step after `init`

**Comment by coreyja** [comment]
@connorshea I haven't been able to convert my project to Tapioca, but I am using sorbet-rails with it today. 

I also haven't tried tapioca again, after learning more about the workflow. 

From my current understanding I would not use the sorbet-typed rbi files, and would try to use tapioca to replace sorbet-rails as well. It sounds like I might want to wait for a 1.0 releases for full rails support potentially though as well. Is that correct?

**Comment by connorshea** [comment]
I'm not sure :) I just converted [vglist](https://github.com/connorshea/vglist) to use tapioca instead of `srb rbi gems` but left sorbet-rails and sorbet-typed, and it seems to work fine.

**Comment by bmulholland** [comment]
Just consolidating steps together as I do them:

- Get a clean start for gem RBI `git rm -rf sorbet/rbi/gems`
-  Add `gem 'tapioca', require: false` to Gemfile development group
- `bundle exec tapioca init`
- `bundle exec tapioca require`
- Edit `sorbet/tapioca/require.rb` and fix if anything is obviously wrong
- `bundle exec tapioca sync` - this error'd on a few gems (vcr, rspec-rails); I removed those from `sorbet/tapioca/require.rb` as they came up, then re-ran the sync
- `bundle exec srb rbi hidden-definitions`
- `bundle exec tapioca todo`
- `bundle exec srb rbi suggest-typed`
- `bundle exec srb tc` -> no errors
- `git diff app` -> Several files have been upgraded in strictness. A couple were downgraded. Overall it looks good!

**Comment by vinistock** [comment]
Hello, folks. Please refer to the [guide for migrating to Tapioca](https://github.com/Shopify/tapioca/wiki/Migrating-to-Tapioca) and let us know if you find any issues.
