### ISSUE TITLE
tapioca 0.10: tapioca dsl hangs when Rails app uses EventedFileUpdateChecker

### ISSUE THREAD

**Issue by bmulholland** [Shopify/tapioca#1149]
tapioca 0.9.4 would finish and exit no problem. When I upgrade to 0.10 `tapioca dsl` completes, but hangs until killed. This happens only when the number of processes for `Parallel` is >1, line ~31 of `Tapioca::Executor`, and it only happens when the rails app is initialized with `config.file_watcher = ActiveSupport::EventedFileUpdateChecker`

One workaround is to use the default Rails file watcher, removing that config. Another is to set workers to 1 with `--workers 1`, though this is incompatible with `--verify` in e.g. git hooks.

I tried tracing it and the exe/tapioca file gets to the end, but the process never closes. A simple repro is to change tapioca's DSL `execute` to:

```ruby
        Loaders::Dsl.load_application(
          tapioca_path: @tapioca_path,
          eager_load: @requested_constants.empty?
        )

        Parallel.map([1,2,3], { in_processes: 2 }){}
        say("done")
        return
```

MBP M1 Pro

Here's the last of the output:

```
Done

Checking generated RBI files...  Done
  No errors found

All operations performed in working directory.
Please review changes and commit them.
^C
```

**Comment by dirceu** [comment]
@bmulholland thank you very much for the investigation! Can you please check if this works for you? https://github.com/Shopify/tapioca/pull/1179
