### ISSUE TITLE
Rake tasks

### ISSUE THREAD

**Issue by lopopolo** [Shopify/tapioca#1155]
Hello, I stumbled across an old issue in Sorbet's GitHub Issues around shipping a Rake task for common sorbet operations:

- https://github.com/sorbet/sorbet/issues/3894

I was curious whether the Tapioca maintainers would be interested in shipping a Sorbet typecheck rake task to fill this void in the ecosystem. In addition, it would be great to have rake tasks for common tapioca operations like `tapioca gems` and `tapioca annotations`,

I was imagining something like:

```
rake tapioca:gems
rake tapioca:annotations
rake sorbet:tc
```

**Comment by rafaelfranca** [comment]
Thank you for the issues. What value would those Rake tasks brings that the current CLIs can't provide?

**Comment by lopopolo** [comment]
I like to roll up all of my pre-push checks into `bundle exec rake lint`. I can do this with `sh` rules in the `Rakefile` but gems like RuboCop and bundler-audit make it a bit easier by allowing me to just instantiate the fake task from upstream, which means I don't need to worry about holding the CLI wrong.

**Comment by lopopolo** [comment]
I have a lot of muscle memory around managing my dev tasks with rake. Learning a new CLI and remembering to invoke it is just a little extra friction.

**Comment by rafaelfranca** [comment]
I see. Thank you for providing more context.

Rails for years is pushing away from Rake tasks. Most Rails commands are not Rake tasks anymore and need to be invoked using the Rails CLI. We are following the same path with tapioca.

Rake has a very bad argument interface, it can't take options other than via environment variables. As general, Rake isn't a very good interface for CLIs.

I don't think maintaining two different CLI interfaces will do any good for this project, so I prefer to not have support to Rake tasks if all they will be in an alias to our current CLI.

But nothing stops you from creating those rake tasks and using in your workflow.

Thank you for the suggestions.
