### ISSUE TITLE
Ordering of methods added by custom DSL compiler differs between local env (MacOS) and CI machine (Linux).

### ISSUE THREAD

**Issue by ric2b** [Shopify/tapioca#1173]
(latest **Tapioca version, 0.10.1**)

When generating rbi files with a custom DSL compiler , I get a different ordering of methods depending on whether it runs locally (x86 MacOS) or in CI (Linux docker image). **Both run with the `development` environment**. This causes `tapioca dsl --verify` to fail.

I made a DSL generator for the [`attr_encrypted` gem](https://rubygems.org/gems/attr_encrypted/versions/3.1.0), very similar to [the example in the Tapioca docs](https://github.com/Shopify/tapioca#writing-custom-dsl-compilers).

Here it is: 
```ruby
# typed: true
# frozen_string_literal: true

# Based on: https://github.com/Shopify/tapioca/#writing-custom-dsl-compilers
module Tapioca
  module Compilers
    class AttrEncrypted < Tapioca::Dsl::Compiler
      extend T::Sig

      ConstantType = type_member { { fixed: T.class_of(ApplicationRecord) } }

      sig { override.returns(T::Enumerable[Module]) }
      def self.gather_constants
        # Collect all the classes that include AttrEncrypted
        all_classes.select { |c| c < ApplicationRecord }
      end

      sig { override.void }
      def decorate
        # Create a RBI definition for each class that includes AttrEncrypted
        root.create_path(constant) do |klass|
          # For each encrypted attribute we find in the class
          constant.encrypted_attributes.each_key do |attr_name|
            # Create the RBI definitions for all the missing methods
            klass.create_method(attr_name, return_type: 'T.untyped')
            klass.create_method("#{attr_name}=", parameters: [create_param('value', type: 'T.untyped')], return_type: 'void')
            klass.create_method("#{attr_name}_encrypted", return_type: 'String')
            klass.create_method("#{attr_name}_encrypted=", parameters: [create_param('value', type: 'String')], return_type: 'void')
          end
        end
      end
    end
  end
end
```

I have a few classes using `attr_encrypted` but only one has the ordering issue that causes `tapioca dsl --verify` to fail.

Calling `constant.encrypted_attributes` when it is processing that class  returns `[:shared_secret, :consumer_secret, :access_token, :access_token_secret]` in both environments so I'm not sure what I could do to make the method order stable.

On my laptop the order is:

```ruby
  def access_token; end
  def access_token_secret; end
  def consumer_secret; end
  def shared_secret; end
  def access_token=(value); end
  def access_token_encrypted; end
  def access_token_encrypted=(value); end
  def access_token_secret=(value); end
  def access_token_secret_encrypted; end
  def access_token_secret_encrypted=(value); end
  def consumer_secret=(value); end
  def consumer_secret_encrypted; end
  def consumer_secret_encrypted=(value); end
  def shared_secret=(value); end
  def shared_secret_encrypted; end
  def shared_secret_encrypted=(value); end
  (...)
```

While in CI the `access_token_secret` methods are all in the end for some reason:

```diff
def access_token; end
- def access_token_secret; end
def consumer_secret; end
def shared_secret; end
def access_token=(value); end
def access_token_encrypted; end
def access_token_encrypted=(value); end
-def access_token_secret=(value); end
-def access_token_secret_encrypted; end
-def access_token_secret_encrypted=(value); end
def consumer_secret=(value); end
def consumer_secret_encrypted; end
def consumer_secret_encrypted=(value); end
def shared_secret=(value); end
def shared_secret_encrypted; end
def shared_secret_encrypted=(value); end
+def access_token_secret; end
+def access_token_secret=(value); end
+def access_token_secret_encrypted; end
+def access_token_secret_encrypted=(value); end
(...)
```

**Comment by ric2b** [comment]
@KaanOzkan linked me to a relevant section of the code where it is supposed to sort the methods before output, but that sort is behind a flag that defaults to `false`, maybe on my CI environment that flag is never set to `true` for some reason?

https://github.com/Shopify/rbi/blob/2d0e0143212c5ae8be0692add8f1c657220e34e1/lib/rbi/formatter.rb#L30

**Comment by KaanOzkan** [comment]
That Formatter is configured by tapioca [here](https://github.com/Shopify/tapioca/blob/703ce223ef95b7252480913296881bec7860e221/lib/tapioca/rbi_formatter.rb#L29-L36). And I assume you're using the default formatter while generating DSLs.

The root cause could be that contents of `encrypted_attributes` hash is in different order between local and CI. Although I'd think the sorting would fix the issue once and for all.

**Comment by ric2b** [comment]
Wow, that took a while to figure out...

So the issue is that in the compiler code I pasted above, the `attr_name`'s are symbols, which means the reader method gets created with a symbol name, but the other three methods get created with strings as the name because of the string interpolation.

This then breaks [this line](https://github.com/Shopify/rbi/blob/2d0e0143212c5ae8be0692add8f1c657220e34e1/lib/rbi/rewriters/sort_nodes.rb#L22) because `<=>` between a symbol and a string returns `nil`, and for some reason the `encrypted_attributes` hash is in a different order on the two platforms (as you guessed).

Changing the compiler code to convert all attribute names to strings solves it:

```ruby
constant.encrypted_attributes.transform_keys(&:to_s).each_key do |attr_name|
```
