### ISSUE TITLE
'Cannot find gem' when local gem path has same prefix as project 

### ISSUE THREAD

**Issue by nsimone** [Shopify/tapioca#1174]
Gems with the same path prefix as the current project are getting filtered out of the dependencies list, resulting in `Error: Cannot find gem 'x'` when generating RBIs. I traced through the code and they are getting removed [here](https://github.com/Shopify/tapioca/blob/83b4259f5f3e034d56c572bacb1413ee2b25ec49/lib/tapioca/gemfile.rb#L99) due to the gem path check [here](https://github.com/Shopify/tapioca/blob/8459356eb3f5cda81abc61c0d38de1f98c71693a/lib/tapioca/helpers/gem_helper.rb#L11) returning true.

**Example**
```
|-- my_project/
|-- my_project_runtime/
```

`my_project` Gemfile:
`gem 'my_project_runtime', path: '../my_project_runtime'`

In `my_project`, run `tapioca gem my_project_runtime`

Output:
```
Requiring all gems to prepare for compiling...  Done

Error: Cannot find gem 'my_project_runtime'
```
After changing the directory name to `something_else_runtime`, `tapioca gem` succeeds.

The project I'm running into this on is using v0.9.2

**Comment by paracycle** [comment]
Oh, nice catch. We should stop using `start_with?` and start using proper `Pathname` methods to check for "is under this directory". Thanks for the detailed error report.
