### ISSUE TITLE
tapioca init stucks indefinitely at  - Finding all unresolved constants, this may take a few seconds... 

### ISSUE THREAD

**Issue by maheshloya-coupa** [Shopify/tapioca#1192]
bundle exec tapioca init --verbose

   identical  sorbet/config
   identical  sorbet/tapioca/config.yml
   identical  sorbet/tapioca/require.rb
       force  bin/tapioca
Retrieving index from central repository... /Users/xx/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
Done
Listing gems from Gemfile.lock... Done
**Removing annotations for gems that have been removed...**  Nothing to do
**Fetching gem annotations from central repository...** 
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.4.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

  Fetched aasm
   identical  sorbet/rbi/annotations/aasm.rbi

  Fetched actionmailer
   identical  sorbet/rbi/annotations/actionmailer.rbi

  Fetched actionpack
   identical  sorbet/rbi/annotations/actionpack.rbi

  Fetched actionview
   identical  sorbet/rbi/annotations/actionview.rbi

  Fetched activerecord
   identical  sorbet/rbi/annotations/activerecord.rbi

  Fetched activesupport
   identical  sorbet/rbi/annotations/activesupport.rbi

  Fetched faraday
   identical  sorbet/rbi/annotations/faraday.rbi

  Fetched graphql
   identical  sorbet/rbi/annotations/graphql.rbi

  Fetched railties
   identical  sorbet/rbi/annotations/railties.rbi

  Fetched rainbow
   identical  sorbet/rbi/annotations/rainbow.rbi

  Fetched webmock
   identical  sorbet/rbi/annotations/webmock.rbi

Done
**Removing RBI files of gems that have been removed:**

  Nothing to do.

**Generating RBI files of gems that are added or updated:**

  Nothing to do.

**Checking generated RBI files...  Done**
  No errors found

**All operations performed in working directory.**
**Please review changes and commit them.**

_Finding all unresolved constants, this may take a few seconds..._

=========================================
**_Sorbet/Tapioca versions -_**

sorbet (0.5.10426)
      sorbet-static (= 0.5.10426)
    sorbet-runtime (0.5.10426)
    sorbet-static (0.5.10426-universal-darwin-21)
    sorbet-static-and-runtime (0.5.10426)
      sorbet (= 0.5.10426)
      sorbet-runtime (= 0.5.10426)
    spoom (1.1.12)
      sorbet (>= 0.5.9204)
      sorbet-runtime (>= 0.5.9204)
      thor (>= 0.19.2)
      
    tapioca (0.10.1)
      bundler (>= 1.17.3)
      netrc (>= 0.11.0)
      parallel (>= 1.21.0)
      pry (>= 0.12.2)
      rbi (~> 0.0.0, >= 0.0.14)
      sorbet-static-and-runtime (>= 0.5.9204)
      spoom (~> 1.1.0, >= 1.1.11)
      thor (>= 1.2.0)
      yard-sorbet

**Comment by julienXX** [comment]
Doing a strace on the srb process I only get
```
λ sudo strace -p 15866
strace: Process 15866 attached
wait4(-1,
```
