### ISSUE TITLE
Classes in non-standard directories not having rbi's generated

### ISSUE THREAD

**Issue by philsmy** [Shopify/tapioca#1193]
we have a Rails app which has the following structure:

```
app
- controllers
- denormalizers
- models
- services
- workers
```

And some others.
We are trying to add Sorbet, but, classes in `services` and `denormalizers` are not having `rbi` files generated for them (though `workers` does).
Do we/can we configure Tapioca so that additional directories are recognized?
The app itself is working fine (this is a legacy app that we are adding Sorbet to).

**Comment by robthornton** [comment]
This file would not have an RBI generated for it. It is not dynamically generated by Rails (DSL) nor is it a gem. You need to type this file yourself and add the `typed` magic string comment.
