### ISSUE TITLE
Why `tapioca` needs Bundler?

### ISSUE THREAD

**Issue by abitrolly** [Shopify/tapioca#1198]
From https://github.com/Shopify/tapioca/issues/1176#issuecomment-1250822334

> Tapioca, specifically, requires being a part of the Bundler workflow

Why? And is it possible to decouple `tapioca` from `bundle` so that it can be a standalone binary?

**Comment by abitrolly** [comment]
> Tapioca needs to be able to figure out the set of gems that a project depends on so that it can generate the gem RBIs for those gems. That information is provided by Bundler

Why it doesn't execute Bundler to get that information, instead of being executed by Bundler itself?

**Comment by abitrolly** [comment]
> What is your use-case? What are you trying to do that is not possible with the tooling as they exist today?

I am trying to build project symbols and upload them to Sourcegraph https://docs.sourcegraph.com/code_navigation/explanations/precise_code_navigation

**Comment by paracycle** [comment]
> I am trying to build project symbols and upload them to Sourcegraph https://docs.sourcegraph.com/code_navigation/explanations/precise_code_navigation

I am familiar with the SCIP tool but I don't understand how that relates to Tapioca, since Tapioca does not do any project symbol resolution. The only thing it does for projects is to create RBIs for runtime generated methods, but srb tooling can mostly do that too.
