### ISSUE TITLE
Tapioca overrides `RAILS_ENV`

### ISSUE THREAD

**Issue by mclark** [Shopify/tapioca#1261]
While getting Tapioca DSL verification running in CI, I was surprised to learn that it was trying to run in the `development` environment even though our CI is in `test`. This is easily overridden by specifying `tapioca dsl -e test` but it would be nice if by default tapioca would respect the system environment.

So the order of precedence from least to greatest would be "Tapioca default of `development`" < "system environment" < "tapioca command argument":

| `RAILS_ENV` from system environment | `Tapioca --environment` | Tapioca runtime `RAILS_ENV` |
|--------|--------|--------|
| `<unspecified>` | `<unspecified>` | `development` |
| `<unspecified>` | `foo` | `foo` |
| `bar` | `foo` | `foo` |
| `bar` | `<unspecified>` | `bar` |

Is this a change that would be considered acceptable? If so, I'd be happy to provide a PR.

**Comment by KaanOzkan** [comment]
Hey @mclark thanks for the report. I let this one slip but yes I think this is a great idea, a PR is very welcome 🙂
