### ISSUE TITLE
add support for `money-rails`

### ISSUE THREAD

**Issue by stathis-alexander** [Shopify/tapioca#1289]
Hello! Tapioca is awesome. Unfortunately, we are unable to use it to generate types for our models due to a lack of support for the [`money-rails` gem](https://github.com/RubyMoney/money-rails). 

Specifically, `money-rails` adds a `monetize` method which takes a column representing the cents amount and adds, among others, a method to access the money object directly. For instace,
```
# has a column `price_cents`
class Product < ActiveRecord::Base
  monetize :price_cents
end
```
would expose the method `price` returning a Money object obtained from monetizing the `price_cents` column. 

Would it be possible for support to be added? Thanks!

**Comment by Morriar** [comment]
👋 Hey Alexander,

Thanks for your interest in Tapioca.

You can [write a custom generator](https://github.com/Shopify/tapioca#writing-custom-dsl-compilers) for this gem and place it inside the sorbet/tapioca/compilers directory of your application.

Hope this helps.

**Comment by stathis-alexander** [comment]
Wow, this one is old! For anyone that lands here in the future, we've added our `MoneyRails` compiler to our Boba repo. https://github.com/angellist/boba
