### ISSUE TITLE
Fix flakyness on CI

### ISSUE THREAD

**Issue by paracycle** [Shopify/tapioca#1306]
We have some recurring problems that keep popping up on CI:
1. Bundler/gemspec related error: `rubygems/specification.rb:2121:in 'method_missing': undefined method 'identifier' for #<Gem::Specification:0x0000562ed629c100> (NoMethodError)`
    - https://github.com/Shopify/tapioca/actions/runs/3650000604/jobs/6165419530#step:5:588
    - https://github.com/Shopify/tapioca/actions/runs/3643033170/jobs/6150808732#step:5:62
    - https://github.com/Shopify/tapioca/actions/runs/3643012213/jobs/6150769063#step:5:704
2. `PP::ObjectMixin` flakiness on Rails 6.1 tests: 
    - https://github.com/Shopify/tapioca/actions/runs/3633766682/jobs/6131151159#step:5:485
    - https://github.com/Shopify/tapioca/actions/runs/3633749602/jobs/6131114809#step:5:386

**Comment by paracycle** [comment]
For now, both issues seem to be address to various degrees of effectiveness. Will reopen if we see regressions.

**Comment by KaanOzkan** [comment]
Listing regressions here as I observe them:

- Caught one in the most recent dependabot merge https://github.com/Shopify/tapioca/actions/runs/3761036498/jobs/6392358002#step:6:553
