### ISSUE TITLE
tapioca init errors out

### ISSUE THREAD

**Issue by ejstembler** [Shopify/tapioca#1367]
Running `bundle exec tapioca init` errors out.  It starts out fine:

```console
   identical  sorbet/config
   identical  sorbet/tapioca/config.yml
   identical  sorbet/tapioca/require.rb
       force  bin/tapioca
Retrieving index from central repository... Done
Listing gems from Gemfile.lock... Done
Removing annotations for gems that have been removed...  Nothing to do
Fetching gem annotations from central repository... 

  Fetched activesupport
   identical  sorbet/rbi/annotations/activesupport.rbi

  Fetched faraday
   identical  sorbet/rbi/annotations/faraday.rbi

  Fetched rainbow
   identical  sorbet/rbi/annotations/rainbow.rbi

Done
Removing RBI files of gems that have been removed:

  Nothing to do.

Generating RBI files of gems that are added or updated:

Requiring all gems to prepare for compiling...  Done
```

However, it eventually errors out like this:

```console
...
7ff84ec00000-7ff84ee00000 rw-
7ff84ee00000-7ff84f000000 r--
7ff84f000000-7ff84f200000 rw-
7ff84f200000-7ff84fe00000 r--
7ff84fe00000-7ff850000000 rw-
7ff850000000-7ff850200000 rw-
7ff850200000-7ff880000000 r--
7ff880000000-7ffffe000000 r--
7fffffe00000-7fffffe01000 r--
7ffffff1a000-7ffffff1b000 r-x
[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.
```

I don't see a crash report file anywhere.  I'm also not able to capture the output by redirecting `bundle exec tapioca init -V > out.txt`; that only captures the beginning.

**Details**

**OS**: macOS 13.1 (22C65)
**Ruby**: ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin22]
**Project**: This is a Rake project with Rake tasks and it also references a local Gem which is a git submodule

**Gemfile**

```Gemfile
# frozen_string_literal: true

ruby '3.2.0'
source 'https://rubygems.org'

gem 'holidays', '~> 8.4.1'

gem 'rake', '~> 13.0', '>= 13.0.3'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw]

group :development do
  gem 'dalli'
  gem 'sorbet'
  gem 'sorbet-runtime'
  gem 'tapioca'
  gem 'dotenv', '~> 2.7', '>= 2.7.6'
  gem 'rubocop', '~> 1.31', require: false
  gem 'rubocop-rake', require: false
end

gem 'telematics', path: 'gems/telematics/'
```

**Comment by Morriar** [comment]
👋 Hey @ejstembler,

In which project are you running `tapioca init` in? Any chance you can share the Gemfile of this project so we can try to reproduce the error on our side?

Thanks!

**Comment by ejstembler** [comment]
> 👋 Hey @ejstembler,
> 
> In which project are you running `tapioca init` in? Any chance you can share the Gemfile of this project so we can try to reproduce the error on our side?
> 
> Thanks!

Hi @Morriar I've updated the issue with the description of the project and the Gemfile.  It's a Rake project with Rake tasks and it also references a local Gem which is a git submodule.

**Comment by Morriar** [comment]
So I've been trying with the same MacOS version, the same Ruby version than you and the following Gemfile:

```rb
# frozen_string_literal: true

ruby '3.2.0'
source 'https://rubygems.org'

gem 'holidays', '~> 8.4.1'

gem 'rake', '~> 13.0', '>= 13.0.3'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw]

group :development do
  gem 'dalli'
  gem 'sorbet'
  gem 'sorbet-runtime'
  gem 'tapioca'
  gem 'dotenv', '~> 2.7', '>= 2.7.6'
  gem 'rubocop', '~> 1.31', require: false
  gem 'rubocop-rake', require: false
end
```

but couldn't reproduce the error so I suspect the problem is with `telematics`.

**Comment by Morriar** [comment]
This looks like a Ruby error though. Do you have the same problem with Ruby 3.1.3 for example?

**Comment by ejstembler** [comment]
@Morriar Yeah, you may be right.  I reverted to Ruby `3.0.3` and it works without incident now.  Thanks.
