### ISSUE TITLE
net/ssh conflicting definitions between tapioca rbi and built in sorbet rbi

### ISSUE THREAD

**Issue by will** [Shopify/tapioca#142]
With a gemfile
``` ruby
 gem "sorbet"
 gem "tapioca"
 gem "net-ssh"
```

that is all latest resolved as of right now
```
Using ast 2.4.1
Using bundler 2.1.4
Using coderay 1.1.3
Using colorize 0.8.1
Using highline 2.0.3
Using commander 4.5.2
Using method_source 1.0.0
Using net-ssh 6.1.0
Using parser 2.7.1.5
Using rainbow 3.0.0
Using sorbet-runtime 0.5.5933
Using parlour 4.0.1
Using pry 0.13.1
Using sorbet-static 0.5.5933 (universal-darwin-19)
Using sorbet 0.5.5933
Using thor 1.0.1
Using spoom 1.0.4
Using tapioca 0.4.6
```

and a tapioca require file with just `require "net/ssh"`, and nothing else in the project, `srb tc` fails

``` crystal
sorbet/rbi/gems/net-ssh@6.1.0.rbi:167: Method Net::SSH::KnownHosts#keys_for redefined without matching argument count. Expected: 1, got: 2 https://srb.help/4010
     167 |  def keys_for(host, options = T.unsafe(nil)); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/04ef993fe0d075126c2553989a3e1a91f508bd79/rbi/stdlib/net.rbi#L8459: Previous definition
    8459 |  def keys_for(host); end
            ^^^^^^^^^^^^^^^^^^

sorbet/rbi/gems/net-ssh@6.1.0.rbi:176: Method Net::SSH::KnownHosts.search_in redefined without matching argument count. Expected: 2, got: 3 https://srb.help/4010
     176 |    def search_in(files, host, options = T.unsafe(nil)); end
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/04ef993fe0d075126c2553989a3e1a91f508bd79/rbi/stdlib/net.rbi#L8471: Previous definition
    8471 |  def self.search_in(files, host); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 2
```

**Comment by KaanOzkan** [comment]
Looks like sorbet's built in RBI for `net-ssh` needs to be updated. As tapioca correctly generates the `rbi` for the net-ssh v6.1.0:

https://github.com/net-ssh/net-ssh/blob/v6.1.0/lib/net/ssh/known_hosts.rb#L60 

Meanwhile same method in sorbet: https://github.com/sorbet/sorbet/blob/master/rbi/stdlib/net.rbi#L8471

In the meantime you can use the `--typed-overrides [gem:level]` flag of tapioca to bypass this error. It's not a solution of course as you'd have to use strictness level of `false`. More info in readme: https://github.com/Shopify/tapioca#flags

**Comment by will** [comment]
Thanks. I think instead in the meantime I'll manually comment out the offending lines in the tapioca generated one, since nothing I'm doing actually touches any of those lines

**Comment by will** [comment]
I opened an issue on sorbet, feel free to close this one if it's not needed to track it here any more :)
