### ISSUE TITLE
tapioca init fails with syntax error

### ISSUE THREAD

**Issue by pathsny** [Shopify/tapioca#1569]
I have a project using rbenv with ruby 3.2.2. 
Running 
`bundle exec tapioca init`

fails with the error
```
Requiring all gems to prepare for compiling... bundler: failed to load command: tapioca (/Users/vsi/.rbenv/versions/3.2.2/bin/tapioca)
/Users/vsi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/regexp_parser-2.8.1/lib/regexp_parser/syntax/version_lookup.rb:41:in `version_class': Unknown syntax name 'ruby/3.2.2'. (Regexp::Syntax::UnknownSyntaxNameError)
	from /Users/vsi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/regexp_parser-2.8.1/lib/regexp_parser/syntax/version_lookup.rb:23:in `for'
```

Full output and stacktrace here.
https://gist.github.com/pathsny/f8d6537f4f8423a0ccab3848479440ff

**Comment by KaanOzkan** [comment]
Looks like regexp_parser 2.8.1 does work with Ruby 3.2.2 and I can't reproduce this issue. Are you able to run other things like `bundle exec rubocop`? That should also trigger a load for `regexp_parser` gem.
