### ISSUE TITLE
v2.2.0 of `rails-dom-testing` gem RBI generation broken re: `CountDescribable` inlining

### ISSUE THREAD

**Issue by larouxn** [Shopify/tapioca#1593]
Looks like the following change, released in the v2.2.0 release of `rails-dom-testing` has broken its RBI generation.

- https://github.com/rails/rails-dom-testing/commit/1ef961f0acbae3a636a46d8ffe74cd7267b64e46 "Inline CountDescribable module"
- https://github.com/rails/rails-dom-testing/releases/tag/v2.2.0
- https://github.com/rails/rails-dom-testing/compare/v2.1.1...v2.2.0

```shell
sorbet/rbi/gems/actionpack@7.0.6.rbi:7639: Unable to resolve constant CountDescribable https://srb.help/5002
    7639 |  include ::Rails::Dom::Testing::Assertions::SelectorAssertions::CountDescribable
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Did you mean Google::Ads::GoogleAds::V14::Services::CustomVariable? Use -a to autocorrect
    sorbet/rbi/gems/actionpack@7.0.6.rbi:7639: Replace with Google::Ads::GoogleAds::V14::Services::CustomVariable
    7639 |  include ::Rails::Dom::Testing::Assertions::SelectorAssertions::CountDescribable
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sorbet/rbi/dsl/google/ads/google_ads/v14/services/custom_variable.rbi:7: Google::Ads::GoogleAds::V14::Services::CustomVariable defined here
     7 |class Google::Ads::GoogleAds::V14::Services::CustomVariable
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Did you mean ActiveRecord::CounterCache? Use -a to autocorrect
    sorbet/rbi/gems/actionpack@7.0.6.rbi:7639: Replace with ActiveRecord::CounterCache
    7639 |  include ::Rails::Dom::Testing::Assertions::SelectorAssertions::CountDescribable
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sorbet/rbi/gems/activerecord@7.0.6.rbi:16258: ActiveRecord::CounterCache defined here
       16258 |module ActiveRecord::CounterCache
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Seems Rails' RBIs are still referencing `rails-dom-testing`'s `CountDescribable` module which is now inlined.

**Comment by Morriar** [comment]
👋 Hey @larouxn,

I think you just need to regenerate the RBI for `actionpack`: `tapioca gem actionpack`.

I'm going to close this for now, feel free to reopen if the problem persists after regeneration 👍

**Comment by larouxn** [comment]
👋 @Morriar, thanks for the quick response. Indeed needed to regenerate `actionpack` _and_ `actionmailer` and `actionview` as well, various "action" gems. All good now. 🙌 

```shell
bundle exec tapioca gem rails-dom-testing actionpack actionmailer actionview
```

Regenerating removes `CountDescribable` module mentions as desired. 😌 

<img width="939" alt="Screenshot 2023-08-08 at 7 22 05" src="https://github.com/Shopify/tapioca/assets/1557529/536d88d8-a0c6-4756-a2c8-a3f498ab5162">

**Comment by andyw8** [comment]
Might it be an improvement for Tapioca to automatically regenerate a dependency's parent dependency RBIs when using `tapioca gem`? Or would that slow things down too much in other scenarios?

**Comment by Morriar** [comment]
> Might it be an improvement for Tapioca to automatically regenerate a dependency's parent dependency RBIs when using `tapioca gem`? Or would that slow things down too much in other scenarios?

That's the plan: https://github.com/Shopify/tapioca/issues/1576
