### ISSUE TITLE
rubocop-minitest RBI generation leading to type error

### ISSUE THREAD

**Issue by larouxn** [Shopify/tapioca#1619]
👋 Hello again, apologies for another issue but I'm curious if y'all have seen this before. Added `rubocop-minitest` to a Rails project, `bin/tapioca gem` to generate RBI file, and now the following. Looks to be trying to source [RuboCop::Cop::RangeHelp](https://github.com/rubocop/rubocop/blob/342bbbe82043509e006741a88d3413d6a9574480/lib/rubocop/cop/mixin/range_help.rb).

```ruby
bin/typecheck
sorbet/rbi/gems/rubocop-minitest@0.31.0.rbi:19: Unable to resolve constant RangeHelp https://srb.help/5002
    19 |  include ::RuboCop::Cop::RangeHelp
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  Did you mean ActionView::Helpers::Tags::RangeField? Use -a to autocorrect
    sorbet/rbi/gems/rubocop-minitest@0.31.0.rbi:19: Replace with ActionView::Helpers::Tags::RangeField
    19 |  include ::RuboCop::Cop::RangeHelp
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
    sorbet/rbi/gems/actionview@7.0.7.2.rbi:10212: ActionView::Helpers::Tags::RangeField defined here
       10212 |class ActionView::Helpers::Tags::RangeField < ::ActionView::Helpers::Tags::NumberField; end
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Have so far tried:
- `bin/tapioca gem`
- `bin/tapioca dsl`
- `bundle update tapioca`

**Comment by Morriar** [comment]
You may need to [manually require part of the gem](https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem). Looking at the [RangeHelp class](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/mixin/range_help.rb), it seems it's defined under `rubocop/cop/mixin/range_help.rb`. Can you try to add it to your `sorbet/tapioca/require.rb` then regenerate the gem RBI again?

**Comment by larouxn** [comment]
> Then ran `tapioca gem --all` and the generated RBI for `rubocop` does contain `RuboCop::Cop::RangeHelp` so I'm not sure what the problem may be.
> 
> Did you regenerate the RBIs for `rubocop` with `tapioca gem rubocop`?

This is the primary issue, we're lacking a RuboCop RBI file. Added RuboCop to Gemfile, was using implicitly until now, as well as to `sorbet/tapioca/require.rb` but no luck. `tapioca gem` will not generate but rather burns any `rubocop@some_ver.rbi` that is added to the repo; just to see manually added one. Definitely a strange loading issue.

<img width="916" alt="Screenshot 2023-08-30 at 8 15 55" src="https://github.com/Shopify/tapioca/assets/1557529/15b9819c-dc97-4510-b94d-b3e5734aa708">

Anyway, this is not specific to `rubocop-minitest` but rather our repo's strange lack of a RuboCop RBI file, thus closing.
