### ISSUE TITLE
ActiveRecord::Concern and reusing DSLs in other DSLs?

### ISSUE THREAD

**Issue by Overload119** [Shopify/tapioca#1633]
Given a Concern intended to be on ActiveRecord.

```rb
module Requestable
  extend T::Helpers
  extend T::Sig
  extend ActiveSupport::Concern

  requires_ancestor { ApplicationRecord }

  included do
    T.bind(self, T.untyped)

    has_one :request, as: :requestable, touch: true, dependent: :nullify
    has_many :proposals, through: :request
  end
end
```

I'm assuming out of the box I can't get this to work, however, is there a way to get my custom DSL compiler to re-use the ActiveRecord one?

I'm looking to define the `request` and `proposals` on the ApplicationRecords that `include Requestable`

**Comment by KaanOzkan** [comment]
Does the association compiler not generate them? https://github.com/Shopify/tapioca/blob/main/lib/tapioca/dsl/compilers/active_record_associations.rb

**Comment by Qqwy** [comment]
I can confirm that it _does_ work correctly where the association compiler is able to see the `has_one` and `has_many`.

@Overload119 one more trick you can do, is replace

```ruby
  included do
    T.bind(self, T.untyped)
    ...
end
```

with

```ruby
  included do
    T.bind(self, T.all(T.class_of(ApplicationRecord), T::Class[Requestable]))
    ...
end
```

which allows Sorbet to check that you use only methods available to ApplicationRecord or defined as part of your new concern in there :-) .

**Comment by paracycle** [comment]
@Overload119 Based on how the `ActiveRecordAssociation` compiler is expected to work, and given @Qqwy's comments, I think this is not an issue, so I'll close it.
