### ISSUE TITLE
DSL with custom compilers has different output on different platforms

### ISSUE THREAD

**Issue by alex-tan** [Shopify/tapioca#1665]
We have used custom code to generate rbis for a while but we're trying to migrate them to use Tapioca compilers. I migrated the code which seemed to work fine but then realized the output was different when running locally on MacOS vs running inside on a Docker image based on `ubuntu:20.04`. Most rbis are the same between platforms but a small percentage look like this:

```diff
--- a/mac_os/email_message.rbi
+++ b/linux/email_message.rbi
@@ -82,12 +82,12 @@ class EmailMessage
   sig { params(value: T.untyped).returns(T.untyped) }
   def raw_message=(value); end
 
-  sig { params(value: T.untyped).returns(T.untyped) }
-  def raw_message=(value); end
-
   sig { returns(T::Boolean) }
   def raw_message?; end
 
+  sig { returns(T::Array[T.untyped]) }
+  def raw_to; end
+
   sig { params(value: T::Array[T.untyped]).returns(T::Array[T.untyped]) }
   def raw_to=(value); end
 
@@ -103,12 +103,12 @@ class EmailMessage
   sig { returns(Paperclip::Attachment) }
   def raw_message; end
 
+  sig { params(value: T.untyped).returns(T.untyped) }
+  def raw_message=(value); end
+
   sig { returns(T::Boolean) }
   def raw_message?; end
 
-  sig { returns(T::Array[T.untyped]) }
-  def raw_to; end
-
   private
 
   sig { returns(NilClass) }
 ```

As you can see the definitions are the same it's just that the methods have been ordered differently. This prevents `dsl --verify` from working on different platforms.

**Comment by KaanOzkan** [comment]
Hmm then I'd take a closer look at the specific compiler. It's not happening with default compilers so overall formatting must be fine. I'm also surprised that there already is a `raw_message=` definition in your diff that's unchanged. Looks like it's duplicated
<img width="500" alt="Screenshot 2023-09-21 at 2 14 46 PM" src="https://github.com/Shopify/tapioca/assets/16736048/7f75f634-5628-4166-bf8a-4fb18a65ba1f">

**Comment by paracycle** [comment]
As @KaanOzkan said above, the diff shown does look suspicious, especially since `EmailMessage` seems to have 2 sets of `raw_message=`, `raw_message?`.

Since we can't reproduce this problem on our end, we won't be able to fix it either. If you can supply a reproduction case for us (a gist, or a small repo would do), then please feel free to reopen this issue so that we can analyze it.

**Comment by alex-tan** [comment]
Thanks to both of you for the detailed responses. I have stopped working on that portion of our code at the moment but I will keep your advice in mind if I revisit the issue.
