### ISSUE TITLE
Rails dependencies actionmailer and mail sorbet/rbi/gems rbi files are empty: Unable to resolve constant Mail

### ISSUE THREAD

**Issue by yesthesoup** [Shopify/tapioca#1666]
Coming over here from `rbi-central` https://github.com/Shopify/rbi-central/issues/177

Rails latest 7.0.8, fresh project, fresh install of latest sorbet/tapioca. Ran `bin/tapioca gem` to generate from installed gems.

Latest gems installed:

```sh
> bundle list | ack '(sorbet|tapioca)'
  * sorbet (0.5.11032)
  * sorbet-runtime (0.5.11032)
  * sorbet-static (0.5.11032)
  * sorbet-static-and-runtime (0.5.11032)
  * tapioca (0.11.9)
  * yard-sorbet (0.8.1)
```

```sh
> bundle exec srb tc
sorbet/rbi/annotations/actionmailer.rbi:8: Unable to resolve constant Mail https://srb.help/5002
     8 |  sig { params(headers: T.untyped, block: T.nilable(T.proc.void)).returns(Mail::Message) }
                                                                                  ^^^^
  Did you mean Spoom::Cli::Main? Use -a to autocorrect
    sorbet/rbi/annotations/actionmailer.rbi:8: Replace with Spoom::Cli::Main
     8 |  sig { params(headers: T.untyped, block: T.nilable(T.proc.void)).returns(Mail::Message) }
                                                                                  ^^^^
    sorbet/rbi/gems/spoom@1.2.3.rbi:217: Spoom::Cli::Main defined here
     217 |class Spoom::Cli::Main < ::Thor
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Did you mean ActionMailer::Base? Use -a to autocorrect
    sorbet/rbi/annotations/actionmailer.rbi:8: Replace with ActionMailer::Base
     8 |  sig { params(headers: T.untyped, block: T.nilable(T.proc.void)).returns(Mail::Message) }
                                                                                  ^^^^
    sorbet/rbi/annotations/actionmailer.rbi:7: ActionMailer::Base defined here
     7 |class ActionMailer::Base
        ^^^^^^^^^^^^^^^^^^^^^^^^
```

I see here in the tapioca project [mail@2.8.1.rbi](https://github.com/Shopify/tapioca/blob/main/sorbet/rbi/gems/mail%402.8.1.rbi) and [actionmailer@7.0.8.rbi](https://github.com/Shopify/tapioca/blob/main/sorbet/rbi/gems/actionmailer%407.0.8.rbi) are non empty, but mine are empty, and explicitly calling `tapioca gem` for either of these for whatever reason doesn't recognise that it should update them.

![image](https://github.com/Shopify/tapioca/assets/2483953/1b79b192-5de7-4c70-90ea-48f87bdc1eb4)

Note `(empty output)` below
```sh
> bin/tapioca gem mail
Requiring all gems to prepare for compiling...
 Done

Removing RBI files of gems that have been removed:

  Nothing to do.

  Compiled mail (empty output)
   identical  sorbet/rbi/gems/mail@2.8.1.rbi

Checking generated RBI files...  Done
  No errors found
```

Same with `actionmailer`.

How can I solve this without copy/pasting from this repo? Any next steps to try? Thank you

**Comment by KaanOzkan** [comment]
When you run `bin/rails console` and evaluate `ActionMailer` is it found or do you get an uninitialized constant error?

**Comment by yesthesoup** [comment]
> When you run `bin/rails console` and evaluate `ActionMailer` is it found or do you get an uninitialized constant error?

I double checked they were installed first

```sh
> bundle list | ack mail
  * actionmailbox (7.0.8)
  * actionmailer (7.0.8)
  * mail (2.8.1)
```

then you're right, they're undefined

```ruby
> rails c
...
Loading development environment (Rails 7.0.8)

 Welcome to sorbet_test development, version ?

[1] sorbet_test#deve(main)> defined?(ActionMailer)
=> nil
[2] sorbet_test#deve(main)> ActionMailer
NameError: uninitialized constant ActionMailer
from (pry):2:in `__pry__'
[3] sorbet_test#deve(main)> Mail::Message
NameError: uninitialized constant Mail
from (pry):3:in `__pry__'
```

but if I import them, they are there
```ruby
Loading development environment (Rails 7.0.8)

 Welcome to sorbet_test development, version ?

[1] sorbet_test#deve(main)> require "action_mailer"
=> true
[2] sorbet_test#deve(main)> defined?(ActionMailer)
=> "constant"
[3] sorbet_test#deve(main)> require "mail/message"
=> true
[4] sorbet_test#deve(main)> defined?(Mail::Message)
=> "constant"
```

**Comment by yesthesoup** [comment]
> Okay that's it then. You might want `require "rails/all"` in your `config/application.rb` to handle this one and any others in the future. If your application loads the constant upon boot it'll be available for tapioca to process it during `bin/tapioca dsl` since `dsl` command loads your applications.

Thanks for your help!

**Comment by yesthesoup** [comment]
Update for anyone coming to this issue: after learning more about Sorbet I've determined that `sorbet/rbi/annotations/actionmailer.rbi` probably should not have been fetched when `tapioca init` was first run, and I have raised an issue here https://github.com/Shopify/tapioca/issues/1696 to discuss this. Temp solution is just to delete the `actionmailer.rbi` file.
