### ISSUE TITLE
Generate `mixes_in_class_methods` when a module extends other modules

### ISSUE THREAD

**Issue by KaanOzkan** [Shopify/tapioca#1678]
I haven't taken a detailed look but I'm hoping that annotations such as [this](https://github.com/Shopify/rbi-central/blob/324d693e20ef959afc1d4217e8d276cc07a72e43/rbi/annotations/graphql.rbi#L54C7-L54C7) can be automatically inserted by Tapioca.

In this specific case we have a module (`HasFields`) that defines methods which is then [extended into](https://github.com/Shopify/tapioca/blob/v0.11.9/sorbet/rbi/gems/graphql%402.1.0.rbi#L9708) `Interface`. As a result, inside `Interface` module these methods are class methods and require `mixes_in_class_methods` calls to be available to Sorbet.

**Comment by paracycle** [comment]
I don't understand what the request is here. If `Interface` extends `HasFields`, then that won't propagate as a `mixes_in_class_methods` to any class that includes `Interface`. 

**The ancestors of singleton classes of modules never get mixed into anything.**

Can you give an example of what kind of code is failing and how?

**Comment by KaanOzkan** [comment]
You're right the title is incorrect.

I think I just wanted to see if we can detect the dynamic mixins and make them explicit using `mixes_in_class_methods` that are happening inside GraphQL gem. It looks like there are [`included` blocks](https://github.com/rmosolgo/graphql-ruby/blob/9b0988e998a95ceca17ae752bed355d9e4842760/lib/graphql/schema/member/has_fields.rb#L171-L175) and there's that `definition_methods` usage you pointed out. I can't find the exact methods that caused this shim so I can't investigate further and give a better description. I'll close the issue.
