### ISSUE TITLE
Gem RBI generation is missing Rails engines files after upgrading to v0.11.10

### ISSUE THREAD

**Issue by olivier-thatch** [Shopify/tapioca#1706]
Like it says on the tin... I bumped Tapioca to v0.11.10 and ran `tapioca gem` and all (or at least many) files loaded from Rails engines are now ignored and no longer part of the generated RBIs.

E.g. we're using the [maintenance_tasks](https://github.com/Shopify/maintenance_tasks) gem, and now `sorbet/rbi/gems/maintenance_tasks@2.3.3.rbi` is missing definitions for `MaintenanceTasks::ApplicationController`, `MaintenanceTasks::Task`, etc.

AFAICT, same thing happens for all of our gems that include Rails engines (blazer, console1984, audits1984, turbo-rails...).

I assume this is caused by #1702 somehow. We are using Rails 7.0.8.

cc @vinistock

**Comment by vinistock** [comment]
Thanks for reporting the bug. That change did cause the issue and #1707 should fix it.
