### ISSUE TITLE
Merging attributes with annotations fails

### ISSUE THREAD

**Issue by vinistock** [Shopify/tapioca#1709]
When addressing https://github.com/ruby/prism/pull/1767, I noticed that all of the type annotations associated with `attr_reader` were being lost. I believe we may be incorrectly merging type signatures for attributes.

Example:

```ruby
# my_gem/rbi/some_file.rbi

class Foo
  sig { returns(Integer) }
  attr_reader :bar
end
```

When Tapioca generates the resulting RBI for `my_gem`, it should include the signature

```ruby
# sorbet/rbi/gems/my_gem@0.1.0.rbi

class Foo
  sig { returns(Integer) } # this is missing
  def bar; end
end
```

**Comment by vinistock** [comment]
I'm not sure that was the exact case we were seeing in Prism. The shims under `rbi` were using attributes

```erb
    sig { returns(<%= field.rbi_class %>) }
    attr_reader :<%= field.name %>
```

And so is the [actual code](https://github.com/ruby/prism/blob/ec2faa9d01beb90f7db22797a70c6291f7d43380/templates/lib/prism/node.rb.erb#L48). Both were defined as attributes, but Tapioca seemed to be dropping them.

**Comment by amomchilov** [comment]
So, my initial inclination here was to first fix the "`sig` getting dropped problem" in this issue, then make a new issue for the "performance improvement: rewrite `attr_*` into `def` methods" (from [Ufuk's comment](https://github.com/Shopify/tapioca/issues/1709#issuecomment-1881784382)).

After looking into this, I don't think that approach is tenable, and I suggest we go right for rewriting `attr_*` into `def` methods, and making sure the sigs work on that.

<hr>

The current implementation says that [`Attr` is incompatible with `Method`](https://github.com/Shopify/rbi/blob/556e9650eb23b7d51a83d851a4592a8f1aba4883/lib/rbi/rewriters/merge_trees.rb#L413), and [vice versa](https://github.com/Shopify/rbi/blob/556e9650eb23b7d51a83d851a4592a8f1aba4883/lib/rbi/rewriters/merge_trees.rb#L462).

This means they're never merged at all. Whatever was on the "left" side of the comparison, is what was kept.

<details><summary><code>example_tests.rb</code></summary>

```rb
# typed: true
# frozen_string_literal: true

require "test_helper"

module RBI
  class NodeMergingTest < Minitest::Test
    LEFT = Rewriters::Merge::Keep::LEFT

    def test_merge_attr_with_attr
      attr1 = Parser.parse_string(<<~RBI)
        attr_reader :a
      RBI

      attr2 = Parser.parse_string(<<~RBI)
        sig { returns(Integer) }
        attr_reader :a
      RBI

      assert_equal(attr2.string, attr1.merge(attr2).string)
      assert_equal(attr2.string, attr2.merge(attr1).string)
    end

    def test_merge_attr_and_method_characterization_test
      attr = Parser.parse_string(<<~RBI)
        sig { returns(Integer) }
        attr_reader :a
      RBI

      method = Parser.parse_string(<<~RBI)
        def a; end
      RBI

      assert_equal(attr.string, attr.merge(method, keep: LEFT).string)
      assert_equal(method.string, method.merge(method, keep: LEFT).string)
    end
  end
end
```

</details>

If we wanted to fix the `sig` getting lost, but still keep the current behaviour of out-putting `attr_*`, we would need to modify both of these methods to handle both `Attr` and `Method`, and merge them. This is more complicated than it's worth IMO, especially when you consider a case like:

```rb
sig { returns(Integer) }
attr_reader :a, :b, :c
```

If this was merged with a tree that had a `def a; end`, we'd need to pull the `a` out of that list.
