### ISSUE TITLE
DSL GeneratedAssociationMethods always optional

### ISSUE THREAD

**Issue by dgodd** [Shopify/tapioca#174]
`belongs_to` accepts an `optional` argument to specify whether the field is nilable or not. Much of my code assumes that `belongs_to` will NOT be nil, but the sorbet generated is specifying them to be nilable.

In fact in rails 5.1 `optional: false` became the default (https://github.com/rails/rails/issues/34454) so this probably affects quite a few codebases.

PS. This project is fantastic, the idea of replacing quite a few `srb` commands (and rails_rbi:all) with faster commands from tapioca is very appealing.

I should note, I am happy to attempt work on a PR if that is desirable.

**Comment by paracycle** [comment]
Hello @dgodd. Thanks for taking Tapioca for a spin and reaching out about this. Happy to hear that you like it.

Unfortunately, the correct modelling of an AR model requires us to to make the `belongs_to` associations nilable. And the same for all attributes as well.

Here is why:
```ruby
class Model < ActiveRecord::Base
  belongs_to :user, optional: false
end

model = Model.new
model.user #=> nil
```

Basically, an AR model has existence both as an in-memory object and as an object loaded from the database. Even if the database forbids persisting certain field values, it is still possible for user code to create model instances that have fields with those values.

Our original implementation was actually doing what you were expecting but we came to the realization that the correct typing of attributes and associations was to type them as nilable values.

**Comment by paracycle** [comment]
Having said that, I also want to note one more thing: It is possible to enforce, at runtime, that a model is never instantiated with empty attributes or associations. If Tapioca can be sure that the model has that behaviour at runtime, [it can generate non-nilable attributes](https://github.com/Shopify/tapioca/blob/master/manual/generator_activerecordcolumns.md) (not associations yet, though). We do use that in our codebase for cases where we want more strongly typed models.

We are planning on exposing that as part of Tapioca, however, that would imply a runtime dependency on the gem that has so far been a development/test dependency, so we are trying to be careful with that.
