### ISSUE TITLE
[Feature request] Support ORM Sequel

### ISSUE THREAD

**Issue by nvh0412** [Shopify/tapioca#177]
Hi! tapioca. Thank you for creating an amazing gem, it helps me resolve many problems which I have to deal manually with `sorbet gem`.

We are using ActiveRecord and Sequel gems, both of them inside our codebases. After I tried using Tapioca for Sequel project, just realized that we didn't have any dsl compiler for Sequel, only ActiveRecord at the moment.

Is there any chance that I can request a DSL compiler for Sequel? please let me know if I can contribute to this project too. I'm willing to do it, and again thanks for this great gem.

**Comment by paracycle** [comment]
👋 Hello, thank you so much for using Tapioca. We are super glad that you are having a good time.

We would also love a Sequel DSL compiler for Tapioca but I am afraid we don't use Sequel at Shopify, so none of us have any experience with the gem to be able to build one.

Would you be interested in building one in a PR if we supported you along the way? I think that would be best outcome.
