### ISSUE TITLE
`tapioca gems` stucks

### ISSUE THREAD

**Issue by sei40kr** [Shopify/tapioca#1777]
I'm running `bundle exec tapioca gems` in a Docker container and it stucks after displaying the message `Done`.
There is no error message and it doesn't exit.

```shell-session
/var/app $ bundle exec tapioca gem
Removing RBI files of gems that have been removed:

  Nothing to do.

Generating RBI files of gems that are added or updated:

Requiring all gems to prepare for compiling... You don't have dalli installed in your application. Please add it to your Gemfile and run bundle install
You don't have dalli installed in your application. Please add it to your Gemfile and run bundle install
 Done
```

## Expected Behavior

It should exit after displaying the message `Done`.

## Actual Behavior

It stucks after displaying the message `Done`.

## Additional Information

I'm using Tapioca v0.11.17 in a Docker container (Alpine Linux based) on M1 Mac.

**Host:**

```shell-session
$ uname -a
Darwin work-mbp 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64 arm Darwin
```

**Container:**

```shell-session
/var/app $ uname -a
Linux 54e0fd9f1b18 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 x86_64 Linux
```

I also tried `tapioca gems -w 1 -V` but it stucks as well and there were no additional messages.

This is perhaps related:
https://github.com/Shopify/tapioca/issues/1192

**Comment by andyw8** [comment]
Hi @sei40kr, can you share your versions of:

- Ruby
- Rails
- Tapioca
- Sorbet

**Comment by sei40kr** [comment]
@andyw8 Thank you for your rapid response!

Ruby: 3.2.2
Rails: 7.0.5
Tapioca: v0.11.17

I realised I can't check the version of Sorbet:

```shell-session
/var/app $ bundle exec srb --version
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

**Comment by sei40kr** [comment]
@KaanOzkan 
Excluding `parser` & `rubocop` worked for me. Thank you!
It just seems to be taking a long time to generate RBI files for `parser` & `rubocop`.

I'm closing this issue.
