### ISSUE TITLE
`tapioca dsl` rejects valid values from `--exclude` if they are not loaded

### ISSUE THREAD

**Issue by aalong-tr** [Shopify/tapioca#1786]
I use some automation scripts to simplify managing Sorbet across modules in a monorepo. 
One of these scripts uses the command `tapioca dsl --exclude ActiveRecordFixtures UrlHelpers` 

As of 0.12.0, this command still works fine for the modules that load Rails in its entirety; but on a few simpler gems, the command now fails with:
```
Error: Cannot find compiler 'ActiveRecordFixtures'
Error: Cannot find compiler 'UrlHelpers'
```

Since `tapioca dsl --list-compilers` does not list these entries when run against the impacted gems, modifying my script to check for the available compilers was easy enough; but it would be nice if the `--exclude` flag would accept allowable compilers even when they are not loaded.

**Comment by KaanOzkan** [comment]
I think making them warnings instead is a good solution.
