### ISSUE TITLE
Is there a way to write a compiler that defines multiple `sig` for a single method?

### ISSUE THREAD

**Issue by asterite** [Shopify/tapioca#1789]
For example for `T::Array` there are multiple overloads/sigs for `first` and `first(limit)`. I'd like to be able to do the same with a compiler.

There's `create_method`. I tried calling it twice with the same method name but that ends up creating two methods with two sigs, and Sorbet takes the last definition. I couldn't find anything in the API to do this... but maybe it's possible?

**Comment by asterite** [comment]
Nevermind, I was able to monkey-patch `RBI::Tree` like this (not ideal that you have to repeat parameters, but it works!):

```ruby
  class RBI::Tree
    extend T::Sig

    sig {
      params(
        parameters: T::Array[RBI::TypedParam],
        return_type: String,
      ).returns(RBI::Sig)
    }
    def create_sig(parameters: [], return_type: "T.untyped")
      sig = RBI::Sig.new(return_type: return_type)
      parameters.each do |param|
        sig << RBI::SigParam.new(param.param.name, param.type)
      end
      sig
    end

    sig {
      params(
        name: String,
        sigs: T::Array[RBI::Sig],
        parameters: T::Array[RBI::TypedParam],
        class_method: T::Boolean,
        visibility: RBI::Visibility,
        comments: T::Array[RBI::Comment],
      ).void
    }
    def create_method_with_sigs(name, sigs:, parameters: [], class_method: false, visibility: RBI::Public.new, comments: [])
      return unless Tapioca::RBIHelper.valid_method_name?(name)

      method = RBI::Method.new(
        name,
        sigs: sigs,
        is_singleton: class_method,
        visibility: visibility,
        comments: comments,
      )

      parameters.each do |param|
        method << param.param
      end

      self << method
    end
  end
```

**Comment by asterite** [comment]
I used this to enhance some ActiveRecord methods, specifically for find, first, last and each.

**Comment by bdewater** [comment]
I wanted to open an issue requesting this feature and found this - @KaanOzkan could we re-open it for tracking the request?

Active Record has a bunch of methods that return a single object when given a single value, or multiple when given multiple. The aforementioned find/first/last/each, but also the generated fixture getter methods come to mind as another example. And there are other places like AR Batches where the correct signature should have overloads, but Sorbet doesn't support these yet for keyword args.

And of course there are people's custom compilers in their apps/gems that might want it too.

**Comment by asterite** [comment]
Thank you, this is great! ❤️ 

Next: support overloads when keyword arguments are involved 😁 Just kidding, I know that's much more complex because it's probably on Sorbet's side :-)

**Comment by bdewater** [comment]
Yes that's a Sorbet issue, nothing on Tapioca's end that prevents you from generating such a sig now. Thanks for providing the monkeypatch, it definitely helped :)

BTW as long as the only difference is the presence/absence of a block parameter, overloads with kwargs are possible. The above pull request does this for find_each/find_in_batches/in_batches.
