### ISSUE TITLE
API change in google-protobuf 4.26.0 breaks CI

### ISSUE THREAD

**Issue by KaanOzkan** [Shopify/tapioca#1819]
DSL compiler appears to be broken due to the changes https://github.com/Shopify/tapioca/actions/runs/8265727256/job/22622289790#step:5:802

**Comment by KaanOzkan** [comment]
I think we're dealing with https://protobuf.dev/news/2023-12-27/#ruby-breaking-changes. It looks like changes introduced in https://protobuf.dev/news/2023-04-20/ (3.23.0) are now the only way and `build` is deprecated.

**Comment by paracycle** [comment]
Do mind that the `Google::Protobuf::DescriptorPool#build` method is only being called in tests, so this means that protobuf _tests_ are broken and likely not the code.

We probably just need to change the tests to use the new generated syntax.
