### ISSUE TITLE
`ActiveRecord::TypedStore` DSL compiler does not respect `array: true` for columns

### ISSUE THREAD

**Issue by ipvalverde** [Shopify/tapioca#1910]
If you're using the `ActiveRecord::TypedStore` gem ([reference](https://github.com/byroot/activerecord-typedstore)) and set a column as being `array: true`, the generated rbi will not respect the array indication. Example:

```ruby

class Shop < ActiveRecord::Base
  typed_store :settings do |s|
    s.string(:tags, array: true, default: [], null: false)
  end
end

### Generated RBI:

class Shop
  module StoreAccessors
    sig { returns(String) }
    def tags; end

    # ...
  end
end

```

The expected would be to have the columns that are defined as `array` to have their type wrapped in a `T::Array` type. So for the example above, I would expect the output to be:

```ruby
class Shop
  module StoreAccessors
    sig { returns(T::Array[String]) }
    def tags; end

    # ...
  end
end
```

**Comment by andyw8** [comment]
Related: https://github.com/Shopify/tapioca/issues/1217
