### ISSUE TITLE
`tapioca dsl` fails on Rails 6.1 models due to ActiveRecord::Encryption reference

### ISSUE THREAD

**Issue by aalong-tr** [Shopify/tapioca#1913]
Repo with simple reproduction here: https://github.com/aalong-tr/tapioca-rails-6-encryption

Tapioca version 0.14.3 includes improvements from #1904 to better handle Rails 7 encrypted attribute behaviors. Unfortunately this logic references a constant that does not exist on Rails 6. As a result, the `tapioca dsl` command run against a Rails 6.1 application produces the error:

```
bundler: failed to load command: tapioca (/Users/drew/.rbenv/versions/3.1.4/bin/tapioca)
/Users/drew/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/tapioca-0.14.3/lib/tapioca/dsl/helpers/active_record_column_type_helper.rb:72:in `type_for_activerecord_value': NameError: uninitialized constant ActiveRecord::Encryption (Parallel::UndumpableException)

          when ActiveRecord::Encryption::EncryptedAttributeType
                           ^^^^^^^^^^^^
Did you mean?  Exception
```

**Comment by swiknaba** [comment]
For now, placing this in e.g. your `config/application.rb` file fixes the issue:

```ruby
module ActiveRecord
  module Encryption
    class EncryptedAttributeType; end # rubocop:disable Lint/EmptyClass
  end
end
```
