### ISSUE TITLE
`tapioca gem` mishandling interface in local gem

### ISSUE THREAD

**Issue by aalong-tr** [Shopify/tapioca#2033]
I work on a monorepo that packages some code as local gems, e.g. loaded via `gem 'foo', path: 'gems/foo'` in our Gemfile. 

One of these gems includes the following module:
```ruby
module Foo::SomeInterface
  extend T::Sig
  extend T::Helpers
  interface!

  sig { abstract.params(id: Integer).returns(Money) }
  def call(id); end
end
```

Running `tapioca gem` in the code that depends on this gem produces the following snippet of RBI: 
```ruby
module Foo::SomeInterface
  interface!

  # source://sorbet-runtime/0.5.11558/lib/types/private/methods/_methods.rb#257
  def call(*args, **_arg1, &blk); end
end
```

This RBI is invalid, and triggers `All methods in an interface must be declared abstract https://srb.help/5022` errors pointed at the generated `call` method when I try to run `srb tc`.

**Comment by aalong-tr** [comment]
This was not a Tapioca problem. 

It turns out that gem Foo was not properly `require`-ing the Money gem, causing a silent failure when Sorbet read the sig for this `call` method while generating RBI. When the Foo gem properly requires its dependencies and the sig no longer raises an error, the generated RBI includes the sig and the correct-arity `call` method. 

While this is deeply unfortunate behavior, I'll go ahead and close this issue since it's very much in the wrong place.

**Comment by aalong-tr** [comment]
...actually, per discussion in the Sorbet Slack, this may still be worth discussing here. 

https://github.com/Shopify/tapioca/blob/main/lib/tapioca/gem/listeners/methods.rb#L215-L225

If the above is the relevant lookup mechanism that would have been used in this case, that `rescue` is going a long way to obfuscate problems in cases like this. Are there any plans to add the option to resurface errors encountered in signatures, or something else along those lines to identify why RBI generation is failing in cases like this?

**Comment by KaanOzkan** [comment]
Yeah that makes sense. It's supposed to print to stdout and surface the error if it's rescuing, is it broken? If you can get it working with your local reproduction please feel free to open a PR.

**Comment by KaanOzkan** [comment]
I see thanks for looking. If the output is buried we could have a "summary" at the bottom and repeat any errors like this one.
