### ISSUE TITLE
AASM "Unable to resolve constant PrivateAASMTransition"

### ISSUE THREAD

**Issue by ngan** [Shopify/tapioca#2107]
After upgrading from Tapioca `0.16.3` to `0.16.5`, and regenerating DSL files, we get the following error in models that use AASM:

```
sorbet/rbi/dsl/user.rbi:49: Unable to resolve constant PrivateAASMTransition https://srb.help/5002
  | 49 \|    sig { params(definitions: T.untyped, block: T.nilable(T.proc.bind(PrivateAASMTransition).void)).returns(T.untyped) }                           ; def transitions(definitions = nil, &block); end
  |                                                                            ^^^^^^^^^^^^^^^^^^^^^
```

I suspect it's from this change: https://github.com/Shopify/tapioca/pull/2043

Perhaps the `PrivateAASMTransition` constant needs to be fully expanded?

cc @marknuzz @KaanOzkan

**Comment by KaanOzkan** [comment]
I haven't observed this error. Is `PrivateAASMTransition` not defined in the same RBI file?

You could run a local tapioca version and debug if this line is running https://github.com/Shopify/tapioca/blob/1705eb0ae8389f60048a73c026bcbf438a8e28d0/lib/tapioca/dsl/compilers/aasm.rb#L193.

**Comment by ngan** [comment]
Here's our generated RBI:
![Image](https://github.com/user-attachments/assets/0207ee9e-ee16-4169-a347-c916f9d8321b)

I think the problem is that `PrivateAASMEvent` and `PrivateAASMTransition` are both sitting under `PrivateAASMMachine` but they're declared as `PrivateAASMMachine::PrivateAASMEvent` and `PrivateAASMMachine::PrivateAASMTransition`. So when `PrivateAASMTransition` is referenced, it can't find `PrivateAASMMachine::PrivateAASMTransition`.

**Comment by ngan** [comment]
The problem is on our end. We have a rewritter that flattens constants.
