### ISSUE TITLE
`PrivateRelation` is not aware of class methods

### ISSUE THREAD

**Issue by rzane** [Shopify/tapioca#2118]
ActiveRecord provides two ways to define scopes. The first is `scope`, which Tapioca generates RBI definitions for. ActiveRecord also allows scopes to be defined as class methods:

```ruby
class Post < ActiveRecord::Base
  def self.published
    where(published: true)
  end
end
```

Tapioca's `PrivateRelation` doesn't include these scopes. Referring to one of these scopes produces a type error:

```ruby
Post.all.published
         ^^^^^^^^^ Method published does not exist on Post::PrivateRelation
```

**Comment by paracycle** [comment]
This is not how Active Record works, so this will not be represented by Tapioca by adding these methods to relation classes.

See https://github.com/Shopify/tapioca/pull/2119#issuecomment-2526341932 and https://github.com/Shopify/tapioca/pull/1994#issuecomment-2302624697 for more information.
