### ISSUE TITLE
Make errors from DSL generators more approachable

### ISSUE THREAD

**Issue by paracycle** [Shopify/tapioca#238]
Currently, when an error is raised during the processing of a DSL generator, we fail with a printed stack trace and nothing else. That makes it really hard to debug the failure, since it is not even obvious which source file the generator is failing on.

We need to display better errors that include:
- which generator caused an error
- for which constant
- with what error message and stack trace

**Comment by mutecipher** [comment]
Going to dump some ideas in here, as I'll be away on vacation next week, and want to have this information available if someone decides to pick up some work. 

- [ ] Centralized error handler for `tapioca`
- [ ] Update runs to no longer fail/report errors immediately. Instead, store them in the error handler, and provide errors/warnings after a run has completed
  - Complete a best effort run, get done what we can, but advise what has failed/errored/etc. 
  - We should be able to generate enough information to advise on potential fixes in the source, or what may require a shim
- [ ] Separate concerns between business logic and application UI
  - [ ]  Break up `generators.rb` into separately clearly defined generator classes
    - Invert dependencies and pass in CLI to deal with reporting?
    - Leave reporting to CLI only, and only gather errors/warnings in the generator classes
      - Use the [Mediator pattern](https://refactoring.guru/design-patterns/mediator)(?)
 
This should get us into a good state where we can provide better context surrounding errors encountered during a run while providing _best-effort_ completion and helpful messaging to solve source related issues.

**Comment by mutecipher** [comment]
Closing this after #584 and #578.

Will add/open smaller for focused issues for additional error messages in the future rather than maintaining this issue. 👍🏻
