### ISSUE TITLE
Tapioca::Loader relies on Rails 6+

### ISSUE THREAD

**Issue by bessey** [Shopify/tapioca#239]
Run Tapioca dsl on a Rails 5.2.4.4 app and you'll get this:
```bash
bash-4.4# bundle exec tapioca dsl
Loading Rails application... Creating scope :authorisable_content. Overwriting existing method Objective.authorisable_content.
# ...
bundler: failed to load command: tapioca (/usr/local/bundle/bin/tapioca)
NoMethodError: undefined method `autoloaders' for Rails:Module
Did you mean?  autoloads
               autoload
               autoload?
               autoload_at
  /usr/local/bundle/gems/tapioca-0.4.13/lib/tapioca/loader.rb:112:in `eager_load_rails_app'
# ...
```

Given your test suite uses Rails 5.2 I was struggling to work out how it wasn't causing issues for you, but it appears to be because its being monkey patched in:
https://github.com/Shopify/tapioca/blob/aad17fa218b84aa762a94821d52175d96b7c6a5b/spec/support/repo/config/application.rb#L10
As best I can tell `Rails.autoloaders` is a Zeitwerk thing, or at least a 6 thing
https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#rails-autoloaders

**Comment by paracycle** [comment]
This was released as part of [v0.4.16](https://github.com/Shopify/tapioca/releases/tag/v0.4.16), thanks for reporting the error, and please let us know if this is still not enough to eager-load a Rails 5.2 app.
