### ISSUE TITLE
Support alternative Sorbet install locations

### ISSUE THREAD

**Issue by nathunsmitty** [Shopify/tapioca#245]
Currently, the path of the `sorbet-static` binary is hardcoded in `lib/tapioca/compilers/sorbet.rb`. However, I have a [custom build of Sorbet](https://github.com/sorbet/sorbet/issues/3852#issuecomment-765865954) that I use because Sorbet doesn't yet support my M1 mac. However, when I try to run `tapioca sync` or other tapioca commands, only empty rbi files are generated because tapioca attempts to use a version of Sorbet that crashes on my system.

When running `srb` commands, there's an escape hatch for this issue: [environment variable `SRB_SORBET_EXE`](https://github.com/sorbet/sorbet/blob/47af81c2b70269349fd9f38da3b6ff7f4f593cb3/gems/sorbet/README.md#environment-variables), which allows one to define a custom path to `sorbet-static`. Would it be possible for tapioca to support this variable or a similar env var? There are also other escape hatch approaches (e.g., an argument) if we don't want to use environment variables.

I'm happy to make a PR for this change if it's a feature you'd like to add!

**Comment by paracycle** [comment]
Yes, please, a PR adding a similar env var would be the most flexible implementation. We could try looking up the env var and fallback to the interpolated path inside of the `sorbet-static` gem. 

I guess `TPC_SORBET_EXE` would be an appropriate name for the env variable.
