### ISSUE TITLE
Verbose / debug mode for "tapioca dsl"

### ISSUE THREAD

**Issue by bessey** [Shopify/tapioca#281]
I am trying to debug this error in "tapioca dsl"

```
Loading DSL generator classes... Done
Compiling DSL RBI files...

bundler: failed to load command: tapioca (/usr/local/bundle/bin/tapioca)
Traceback (most recent call last):
         .... trimmed ...
	 7: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/active_record_associations.rb:148:in `populate_associations'
	 6: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/active_record_associations.rb:148:in `each'
	 5: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/active_record_associations.rb:150:in `block in populate_associations'
	 4: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/active_record_associations.rb:227:in `populate_collection_assoc_getter_setter'
	 3: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/active_record_associations.rb:265:in `type_for'
	 2: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/active_record_associations.rb:291:in `polymorphic_association?'
	 1: from /usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/active_record_associations.rb:291:in `polymorphic_association?'
/usr/local/bundle/gems/tapioca-0.4.20/lib/tapioca/compilers/dsl/active_record_associations.rb:290:in `polymorphic_association?': undefined method `through_reflection?' for nil:NilClass (NoMethodError)
bash-5.1# 
```

but since there is no output pertaining to a specific constant, my only option is to review alphabetically how far through all constants `tapioca dsl` got so far, and try to guess what constant its on now. It would be very helpful if there were a `--verbose` flag that output "About to process X::Y::Z` _before_ running, so that I could see on what constant its breaking. Without cracking open the gem / guesswork.

**Comment by paracycle** [comment]
Agreed the error reporting is super cryptic here and I'll look into making it better. However, this looks very much like an error that was raised by one of our applications (reported [here](https://github.com/Shopify/tapioca/issues/233)) which ended up being because of association declaration without the expected association column existing. 

It was something like:
```ruby
class Foo < ActiveRecord::Base
  has_many :bars, through: :baz
end

class Bar < ActiveRecord::Base
end

class Baz < ActiveRecord::Base
end
```
but `Baz` didn't have column named `bar_id` to complete the `has_many through` association.
