### ISSUE TITLE
Trim trailing blank lines in generated files

### ISSUE THREAD

**Issue by paracycle** [Shopify/tapioca#29]
Tapioca ends up creating trailing empty lines, especially when it outputs an empty RBI file. It would be desirable to trim those so that the output is neater and more predictable.

**Comment by Morriar** [comment]
>  when it outputs an empty RBI file

Should it produce empty files?

**Comment by katayounHillier** [comment]
I haven't seen any empty file .

**Comment by Morriar** [comment]
Here's an example of an empty file generated for `websocket-extensions@0.1.4.rbi`: https://github.com/Shopify/shopify/blob/master/sorbet/rbi/gems/websocket-extensions%400.1.4.rbi

I count 48 empty RBIs in Core.

**Comment by katayounHillier** [comment]
We need to delete them. They seem to be  the  left over from year ago. I don't think the latest `tapioca` generate them again. should we delete all the empty file?

**Comment by Morriar** [comment]
Are you sure?

Can you try the following on Core for example:
```
$ rm -rf sorbet/rbi/gems
$ bundle exec tapioca sync
$ cat sorbet/rbi/gems/websocket-extensions@*.rbi
```

The file is empty but still generated.

**Comment by katayounHillier** [comment]
You are correct @Morriar.

**Comment by katayounHillier** [comment]
but this file `websocket_extension@0.1.5.rbi` is generated on `tapioca` under sorbet/rbi/gems and it is not empty. 👀

**Comment by katayounHillier** [comment]
I used `pry` to  debug, I got: 
`uninitialized constant` which is an indicator of missing `include`.
by adding `include "library-name" ` this issue is solved inside tapioca.
I need to do more testing in `shopify/core` to make sure this fix will resolve the issue in core too.
