### ISSUE TITLE
Generating empty file for `activesupport`

### ISSUE THREAD

**Issue by ghiculescu** [Shopify/tapioca#31]
`tapioca` isn't working for me for `activesupport` 5.2.3, and a bunch of other gems. It generates an empty file:

```ruby
# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   tapioca generate activesupport

# typed: false
```

I added some puts statements and I found that this was the command that is running [here](https://github.com/Shopify/tapioca/blob/1616401d95e7ea1e33aa28b1fccd0fe0d1db2be4/lib/tapioca/compilers/symbol_table/symbol_loader.rb#L35): `/Users/alex/.rvm/gems/ruby-2.6.3/gems/sorbet-static-0.5.5258-universal-darwin-18/libexec/sorbet --no-config --print\=symbol-table-json --quiet @/var/folders/zq/bsvhv93151j849l1wtfh7pch0000gn/T/sorbet20200122-23233-fq4mms` (the file path is different each time but that doesn't really matter)

Running that command locally I get:

```
$ /Users/alex/.rvm/gems/ruby-2.6.3/gems/sorbet-static-0.5.5258-universal-darwin-18/libexec/sorbet --no-config --print\=symbol-table-json --quiet @/var/folders/zq/bsvhv93151j849l1wtfh7pch0000gn/T/sorbet20200122-23233-fq4mms
Segmentation fault: 11
```

And without `--quiet` I get

```
$ /Users/alex/.rvm/gems/ruby-2.6.3/gems/sorbet-static-0.5.5258-universal-darwin-18/libexec/sorbet --no-config --print\=symbol-table-json  @/var/folders/zq/bsvhv93151j849l1wtfh7pch0000gn/T/sorbet20200122-23183-9ggl9n
/Users/alex/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/core_ext/module/introspection.rb:13: Unsupported node type Backref https://srb.help/3003
    13 |      parent_name = name =~ /::[^:]+\Z/ ? $`.freeze : nil
                                                  ^^

/Users/alex/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:352: Unsupported node type Backref https://srb.help/3003
     352 |      file_name = $` if file_name =~ /\.rb\z/
                            ^^

/Users/alex/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:402: Unsupported node type Backref https://srb.help/3003
     402 |      path = $` if path =~ /\.rb\z/
                       ^^

/Users/alex/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/testing/isolation.rb:107: include must only contain constant literals https://srb.help/4002
     107 |      include forking_env? ? Forking : Subprocess
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Segmentation fault: 11
```

For context, `srb rbi gems` generates an activesupport rbi fine. Is this expected behaviour?

**Comment by paracycle** [comment]
Ugh, that looks more like a problem with Sorbet actually. Despite the errors raises, Sorbet should not be segfaulting on this type of code.

It seems you are on a Mac. Can you open Console.app and find the stack trace dump that is associated with these segfaults from the `sorbet` executable? It might point to a suspect code location in Sorbet that might be causing the segfault.

Also, if possible could you test the same command with a different (earlier) version of Sorbet please? Let's see if we can narrow it down to a Sorbet version.

**Comment by ghiculescu** [comment]
https://github.com/sorbet/sorbet/pull/2446#issuecomment-577825911

**Comment by paracycle** [comment]
It looks like this is identified and is being fixed in Sorbet: https://github.com/sorbet/sorbet/pull/2532

I'll close this issue for now, please re-open if you find out it is not fully fixed.

**Comment by ghiculescu** [comment]
Yep this works great now :D
