### ISSUE TITLE
Generate gems RBIs for vendored gems

### ISSUE THREAD

**Issue by Morriar** [Shopify/tapioca#343]
Some projects use vendored gems, for example under the `bundler/` directory.

Such gems don't appear in the Gemfile and thus Tapioca doesn't generate any RBI for them.

Since we generally exclude the vendored directory from type-checking, we're getting missing constants and methods.

We should find a way to make Tapioca generate RBI files for vendored gems.

**Comment by dirceu** [comment]
From Ufuk:

> It looks like Tapioca does the right thing about vendored gems because we explicitly check for it: https://github.com/Shopify/tapioca/blob/3528c25b308fafbc9149f1f693529100f9dcc6fd/lib/tapioca/helpers/gem_helper.rb#L16-L19
> 
> On the flip side, we should not be processing any gem that "lives" inside the repo, since it will be type-checked along with the repo itself anyway

I'm gonna go ahead and close this issue; we can reopen if we find a specific use case to replicate the problem.
