### ISSUE TITLE
Can't run `tapioca sync` if you're setting sorbet's `default_checked_level`

### ISSUE THREAD

**Issue by ghiculescu** [Shopify/tapioca#362]
Using:

```
tapioca (0.4.23)
parlour (6.0.0)
```

I'm not sure if this is strictly a tapioca issue, but I figured I'd ask here because I assume Shopify would have had to deal with a similar issue?

Our Rails app has this at the very top of config/application.rb:

```ruby
require "sorbet-runtime"
T::Configuration.default_checked_level = Rails.env.production? ? :never : :always
```

When we run `bundle exec tapioca sync` we get this output:

```
Removing RBI files of gems that have been removed:

  Nothing to do.

Generating RBI files of gems that are added or updated:

  Requiring all gems to prepare for compiling... Traceback (most recent call last):
(snipped)
	 2: from config/application.rb:7:in `<top (required)>'
	 1: from /Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/configuration.rb:117:in `default_checked_level='
/Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/private/runtime_levels.rb:52:in `default_checked_level=': Set the default checked level earlier. There are already some methods whose sig blocks have evaluated which would not be affected by the new default. (RuntimeError)
```

I added a `puts caller` here: https://github.com/sorbet/sorbet/blob/master/gems/sorbet-runtime/lib/types/private/runtime_levels.rb#L42

Here's where it's being called from:

```
/Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/private/methods/decl_builder.rb:210:in `finalize!'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/private/methods/_methods.rb:344:in `run_builder'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/private/methods/_methods.rb:323:in `run_sig'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/private/methods/_methods.rb:233:in `block in _on_method_added'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/private/methods/_methods.rb:431:in `run_sig_block_for_key'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/private/methods/_methods.rb:411:in `maybe_run_sig_block_for_key'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/sorbet-runtime-0.5.6442/lib/types/private/methods/_methods.rb:242:in `block in _on_method_added'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/parlour-6.0.0/lib/parlour/type_parser.rb:391:in `<class:IntermediateSig>'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/parlour-6.0.0/lib/parlour/type_parser.rb:390:in `<class:TypeParser>'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/parlour-6.0.0/lib/parlour/type_parser.rb:17:in `<module:Parlour>'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/parlour-6.0.0/lib/parlour/type_parser.rb:15:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/parlour-6.0.0/lib/parlour.rb:59:in `require'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/parlour-6.0.0/lib/parlour.rb:59:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl/base.rb:4:in `require'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/tapioca-0.4.23/lib/tapioca/compilers/dsl/base.rb:4:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/tapioca-0.4.23/lib/tapioca.rb:20:in `require'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/tapioca-0.4.23/lib/tapioca.rb:20:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/tapioca-0.4.23/lib/tapioca/internal.rb:4:in `require'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/tapioca-0.4.23/lib/tapioca/internal.rb:4:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/tapioca-0.4.23/exe/tapioca:21:in `require_relative'
/Users/alex/.rvm/gems/ruby-2.7.3/gems/tapioca-0.4.23/exe/tapioca:21:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.7.3/bin/tapioca:23:in `load'
/Users/alex/.rvm/gems/ruby-2.7.3/bin/tapioca:23:in `<main>'
/Users/alex/.rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `eval'
/Users/alex/.rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `<main>'
```

The relevant line: https://github.com/AaronC81/parlour/blob/6.0.0/lib/parlour/type_parser.rb#L391

My understanding is that `tapioca` is loading itself + its deps (both of which use `T::Sig`), then it's requiring our app, and then that's crashing. I can't think of a way to work around this without modifying `tapioca` lots.

We added `default_checked_level =` a few days ago, as we are trying to disable sorbet-runtime in production to minimise its overhead. My understanding is Shopify does the same. Did you come across a similar issue?

cc @AaronC81 since technically it's `parlour` that's crashing, though I don't think it's that gem's fault.

**Comment by paracycle** [comment]
I think the problem is that you are actually setting the `default_checked_level` to `:always` in development. Your reading is correct that Tapioca initializes itself and loads as much of the Rails application as it needs to do its generation. We need to load `config/application.rb` so that we can discover Rails engines that are exported from gems.

However, in recent versions Tapioca can only properly work if it prevents as much of runtime type checking as it can (due to some runtime generic type parameter detection shenanigans).

So, what ends up happening is that Tapioca sets the `T::Configuration.default_checked_level` to `:never` and then some code with `sig`s run and then you `config/application.rb` tries to set it to `:always`. But Sorbet runtime raises with the error you get when that happens.

I think the correct way to configure your Rails app is to do something like:
```ruby
require "sorbet-runtime"
T::Configuration.default_checked_level = :never if Rails.env.production?
```
which accepts the default value for any environment other than `production`. That is what we do in our applications.

**Comment by ghiculescu** [comment]
Oh man you’re right. That’s so obvious in hindsight 🤦
