### ISSUE TITLE
tapioca ignore?

### ISSUE THREAD

**Issue by manhhung741** [Shopify/tapioca#381]
Can we support an `.ignore` file that would let tapioca skip the gems listed in the .ingore?

Why? Due to new changes in the bundler, gems can be installed depending on the system now. I have some dependency gems that are installed on mac but not on the production machine. This will also help with ignoring rbi files of gems that have RBI in `sorbet-typed` and gems not used in the production code at all (like tapioca itself).

**Comment by KaanOzkan** [comment]
Currently you can use `typed_overrides` flag to tell tapioca to generate RBIs at a certain type level. In your case I think generating with the file level `false` and `ignore` will solve your issues. For example, at `false` level conflicts with other RBIs will not result in typechecking errors.

To use the flag you can add a sorbet/tapioca/config.yml file with the contents:

```
---
typed_overrides:
  "foo": "false"
```

Or you can pass the flag through the CLI https://github.com/Shopify/tapioca#flags

**Comment by paracycle** [comment]
Another option to use here is the `--exclude` flag of Tapioca to exclude any gems that you don't want to generate RBIs for. You can do the same thing in the config using:
```yaml
---
exclude:
  - "foo"
```
