### ISSUE TITLE
Expose `perform_sync_verification` in the CLI so it can be used as a CI check

### ISSUE THREAD

**Issue by ric2b** [Shopify/tapioca#417]
Sometimes someone updates a gem (or several) and forgets to run `tapioca sync`, causing the checked in RBI files to be for the wrong version.

If the [perform_sync_verification](https://github.com/Shopify/tapioca/blob/eec1ec89a18a4598bc0dc421012ee486045b626a/lib/tapioca/generator.rb#L660) method was accessible from the CLI it could be used as a CI check, ensuring that the rbi files are kept in sync with gem versions.

**Comment by paracycle** [comment]
@ric2b we are little behind on documentation and releases but that is actually exposed as the `--verify` flag for `sync`, since #364 was merged. We just didn't make a release with that in it yet. But it should be available in the next release.
