### ISSUE TITLE
`tapioca dsl` support for `ActiveModel::SecurePassword::ClassMethods`

### ISSUE THREAD

**Issue by shardulbee** [Shopify/tapioca#423]
Hey there 👋  Am I correct in understanding that `tapioca dsl` doesn't generate sigs for dynamic methods inserted by `ActiveRecord::Base#has_secure_password`?  Example:

```ruby
class User < ActiveRecord::Base
  has_secure_password
end
```

**Comment by paracycle** [comment]
From what I can see, the information we need can be discovered in the following way:

1. pre-6.0, if we find the module `ActiveModel::SecurePassword::InstanceMethodsOnActivation` in the ancestor list of the `constant`, then the methods we need to generate can be found by: `ActiveModel::SecurePassword::InstanceMethodsOnActivation.instance_methods(false)` Ref: https://github.com/rails/rails/blob/ff657e73f0b61a7e224a9f158467ed2ec915bd9b/activemodel/lib/active_model/secure_password.rb#L85-L127
2. 6.0 and above, we need to find a module that is an _instance_ of `ActiveModel::SecurePassword::InstanceMethodsOnActivation` in the ancestor list of the `constant`. If we call that module `mod`, then the list of methods is given by: `mod.instance_methods(false)`

So, all in all, I think the following will be a version agnostic way to fetch the methods names to generate:
```ruby
mod = if constant < ActiveModel::SecurePassword::InstanceMethodsOnActivation
  ActiveModel::SecurePassword::InstanceMethodsOnActivation
else
  constant.ancestors.grep(ActiveModel::SecurePassword::InstanceMethodsOnActivation).first
end

methods = mod.instance_methods(false)
```
