### ISSUE TITLE
Add a description to this repo and maybe some tags so people can find it on GitHub

### ISSUE THREAD

**Issue by emilebosch** [Shopify/tapioca#46]
Before this repo was mentioned. I did a GitHub search for sorbet, but unfortunately didn't came back. Maybe its a good idea, to add a description and maybe some tags ? Like sorbet, ruby, type-checking etc? Thanks ❤️

**Comment by paracycle** [comment]
Thanks, I added a description and some tags. Please let me know if you think they can be better.

**Comment by emilebosch** [comment]
Thanks! 💯
