### ISSUE TITLE
Update migration guide for `generate` deprectation

### ISSUE THREAD

**Issue by bmulholland** [Shopify/tapioca#518]
The [migration guide](https://github.com/Shopify/tapioca/wiki/Migrating-to-Tapioca) says to run `bin/tapioca generate` - but doing so gives the warning: `DEPRECATION: The `generate` command will be removed in a future release. Start using `bin/tapioca gem --all` instead.`

The migration guide should therefore suggest that updated command instead.

**Comment by KaanOzkan** [comment]
Updated https://github.com/Shopify/tapioca/wiki/Migrating-to-Tapioca#run-tapioca-gem.
