### ISSUE TITLE
ActiveStorage macro methods failing type checks

### ISSUE THREAD

**Issue by talhasyed** [Shopify/tapioca#557]
When using ActiveStorage macro methods like `has_many_attached` in model files, the type check fails with an error along the lines of:

```
app/models/my_model.rb: Method has_many_attached does not exist on T.class_of(MyModel) https://srb.help/7003
--
has_many_attached :files
^^^^^^^^^^^^^^^^^^^
```

There is a known workaround that involves adding knowledge about the `ActiveStorage::Attached::Model` methods to `ActiveRecord::Base` in a shim file:

```ruby
# typed: true

class ActiveRecord::Base
  include ActiveStorage::Attached::Model
end
```

This workaround should not be required, and the generated .rbi files for ActiveRecord models should already include ActiveStorage related methods.

---
**EDIT**: We can generate this information as part of the `ActiveStorage` generator.

**Comment by talhasyed** [comment]
Thanks, @Shopify/resiliency-alerts 

From a developer experience point of view, though, should the generated .rbi files not include the methods for (in this case) ActiveStorage without having to do the shim workaround? And have tapioca figure out if they need to be included or not? Or is that not possible with Sorbet at this point?

**Comment by paracycle** [comment]
Now that #1389 made it so that Tapioca is running initializers inside Rails engines, it so happens that we are now able to trigger the initializer that is defining this include and generate it in the gem RBI file.
