### ISSUE TITLE
Don't generate empty modules for RBIs

### ISSUE THREAD

**Issue by mutecipher** [Shopify/tapioca#586]
This doesn't need to be addressed in this PR, but it's kind of odd that we generate the empty module and with corresponding include.

How difficult would it be to avoid generating empty modules?

_Originally posted by @vinistock in https://github.com/Shopify/tapioca/pull/584#discussion_r741989048_

**Comment by paracycle** [comment]
We don't generate empty modules for RBIs already. The concern in #584 was for the case when the constant has broken associations and it is actually fine to generate such RBI files for those cases.
