### ISSUE TITLE
ActiveRecord generators break on anonymous classes

### ISSUE THREAD

**Issue by jflinter** [Shopify/tapioca#592]
Hello! First off, thanks for an excellent library, I've been getting deep into it over the last week and am so impressed by the quality of the project.

I'm getting breakages in the ActiveRecord DSL generators (`ActiveRecordColumns`, `ActiveRecordRelations`, and `ActiveRecordScope`) if, at any point before running them, I invoke `ActiveRecord::Base.connection.schema_migration`. This in turn [generates](https://github.com/rails/rails/blob/37c46e859bc53175dba913e61b60042aee216ab1/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L157) an anonymous class:

```rb
Class.new(ActiveRecord::SchemaMigration) do
  define_singleton_method(:name) { schema_migration_name }
  define_singleton_method(:to_s) { schema_migration_name }

  self.connection_specification_name = spec_name
end
```

The issue is that there is now a `MyModel::SchemaMigration` class in `ObjectSpace` (where MyModel is the base model in my application) that is both a) a descendant of `ActiveRecord::Base`, meaning Tapioca will try to generate RBI for it, and b) anonymous, meaning Tapioca won't know where to write it (and will raise an [exception](https://github.com/Shopify/tapioca/blob/4169604043d0cd0a043b156cf63b1bfcf1093f59/lib/tapioca/rbi_ext/model.rb#L57), which is the error I'm actually encountering).

One solution might be to additionally filter constants in the `gather_constants` [method](https://github.com/Shopify/tapioca/blob/4169604043d0cd0a043b156cf63b1bfcf1093f59/lib/tapioca/compilers/dsl/active_record_columns.rb#L130) of each ActiveRecord generator to ones that `Tapioca::Reflection` can find a name for:
```rb
def gather_constants
  descendants_of(::ActiveRecord::Base).reject(&:abstract_class?).select {|c| Tapioca::Reflection.name_for(c)}
end
```

It might even make sense to do this for all generators? Creating classes at runtime with `Class.new` shouldn't blow up Tapioca if a generator happens to find that class in its implementation of `gather_constants`.

**Comment by KaanOzkan** [comment]
Filtering these out in `gather_constants` make sense for all generators. I think we can get away with using `Module.name`.  Added to our sprint 🙂 Thanks.
