### ISSUE TITLE
ActiveRecord Ids should not be nilable

### ISSUE THREAD

**Issue by elfassy** [Shopify/tapioca#600]
According to the tests tapioca generates id columns as nilable:
https://github.com/Shopify/tapioca/blob/3ea298ea1cfc4d0ffc439a5f1ac46dc033aa2d22/spec/tapioca/compilers/dsl/active_record_columns_spec.rb#L80-L81

in our DB we have ids as NOT NULL
```
`id` bigint(20) NOT NULL AUTO_INCREMENT,
```

Whereas other columns respect the null status set in the DB
https://github.com/Shopify/tapioca/blob/3ea298ea1cfc4d0ffc439a5f1ac46dc033aa2d22/spec/tapioca/compilers/dsl/active_record_columns_spec.rb#L174

Logic is:

https://github.com/Shopify/tapioca/blob/main/lib/tapioca/helpers/active_record_column_type_helper.rb#L49
```ruby
    if column_name == @constant.primary_key ||
        column_name == "created_at" ||
        column_name == "updated_at"
      getter_type = "T.nilable(#{getter_type})"
    end
```

What makes primary_key columns special? Curious why they are not treated as other not null columns.

**Comment by CraigChilds94** [comment]
@elfassy 

I believe this is to allow the case where you call `Model.new`

`id, created_at & updated_at` would be `nil`? 

Example:

```ruby
instance = Model.new

# this would be nil and so should be `T.nilable` ?
instance.id
```

**Comment by elfassy** [comment]
@CraigChilds94 that's what I thought at first, but that would mean every column would be nilable, which is not the case, see https://github.com/Shopify/tapioca/blob/3ea298ea1cfc4d0ffc439a5f1ac46dc033aa2d22/spec/tapioca/compilers/dsl/active_record_columns_spec.rb#L174

**Comment by CraigChilds94** [comment]
@elfassy

In this case **every** column should have `T.nilable` however if we were to do this it wouldn't reflect the application behaviour we might want from the type safety on our models.

I guess there's an assumption here that if you were to have a persisted model like you said, that it would not be "nilable" but in reality even if you `new` the Model without a value or `nil` it isn't covered by this DSL.

I'm not quite sure if theres a way we could actually cater for this

**Comment by CraigChilds94** [comment]
@paracycle I think we can close this issue right? It appears as though this behaviour is expected?

**Comment by connorshea** [comment]
This behavior is really surprising to me, and I'd definitely rather have `.id` _not_ be nilable even if can technically be in some niche edge cases.

**Comment by CraigChilds94** [comment]
> @CraigChilds94 that's what I thought at first, but that would mean every column would be nilable, which is not the case, see
> 
> https://github.com/Shopify/tapioca/blob/3ea298ea1cfc4d0ffc439a5f1ac46dc033aa2d22/spec/tapioca/compilers/dsl/active_record_columns_spec.rb#L174-L217
> 
> Post.new.title can return nil, yet title has `sig { returns(::String) } ` as signature. I'm assuming there's something that knows when a record is persisted or not

Taking another look at this, maybe this is actually a bug? and it should be respecting the `null: true` on the fields making them be nillable?

**Comment by rafaelfranca** [comment]
All Active Record attribute are nilable even if the database don't allow null.

Think on `Model.new.id`, that returns `nil` not a value, so the current signature is correct.

**Comment by stathis-alexander** [comment]
Commenting here on this old issue because it's the first one that appears when searching. 

We are attempting to migrate to tapioca from sorbet-rails (which is now deprecated) for generating our active record model types. This issue is unfortunately afflicting many of our classes and would require quite the undertaking to resolve. Admittedly, we are less concerned with 100% type safety around this edge case and would prefer to include the slight risk of misuse for the convenience of not having to assert not-`nil` everywhere. 

That said, I have found a workaround for this issue. It's a bit ugly. In `config/initializers/tapioca.rb`, add the following 
```
if defined?(Tapioca)
  module TapiocaCompilerOverridesLoader
    def load_dsl_compilers
      super

      say('Loading DSL compiler overrides... ')

      Dir.glob([
        "#{@tapioca_path}/overrides/**/*.rb",
      ]).each do |override|
        require File.expand_path(override)
      end

      say('Done', :green)
    end
  end

  module Tapioca
    module Loaders
      class Dsl
        prepend(TapiocaCompilerOverridesLoader)
      end
    end
  end
end
```

This overrides the dsl loader method to load classes and modules from the `sorbet/tapioca/overrides` folder _after the compilers in the gem are loaded_, allowing us to modify the existing compilers. Then in `sorbet/tapioca/overrides/active_record_columns.rb` override the `column_type_for` method in the `ActiveRecordColumnTypeHelper` as such:
```
module Tapioca
  module Dsl
    module Helpers
      class ActiveRecordColumnTypeHelper
        def column_type_for(column_name)
          return ['T.untyped', 'T.untyped'] if do_not_generate_strong_types?(@constant)

          column = @constant.columns_hash[column_name]
          column_type = @constant.attribute_types[column_name]
          getter_type = type_for_activerecord_value(column_type)
          setter_type =
            case column_type
            when ActiveRecord::Enum::EnumType
              enum_setter_type(column_type)
            else
              getter_type
            end


          if column&.null && !attribute_has_unconditional_presence_validation?(column_name)
            getter_type = as_nilable_type(getter_type) unless not_nilable_serialized_column?(column_type)
            return [getter_type, as_nilable_type(setter_type)]
          end

          if Array(@constant.primary_key).include?(column_name) ||
              column_name == 'created_at' ||
              column_name == 'updated_at'
            getter_type = as_nilable_type(getter_type)
          end

          [getter_type, setter_type]
        end

        private

        def attribute_has_unconditional_presence_validation?(attribute)
          model_class_srb = @constant
          model_class_srb < ActiveRecord::Base &&
            model_class_srb.validators_on(attribute).any? do |validator|
              validator.is_a?(ActiveModel::Validations::PresenceValidator) &&
                !validator.options.key?(:if) &&
                !validator.options.key?(:unless) &&
                !validator.options.key?(:on)
            end
        end
      end
    end
  end
end
```

The `attribute_has_unconditional_presence_validation` is borrowed directly from sorbet-rails.
