### ISSUE TITLE
Classes without instance methods don't generate an `initialize` method

### ISSUE THREAD

**Issue by mutecipher** [Shopify/tapioca#617]
That might be because there are no methods in the regular class. I think this might be a bug. Maybe because Sorbet doesn't print any symbols for the regular class, Tapioca never realizes it needs to add an `initialize` method?

_Originally posted by @vinistock in https://github.com/Shopify/tapioca/pull/615#discussion_r751415045_

---

Given the following input:
```ruby
# typed: true
# frozen_string_literal: true

class Foo
  class << self
    def foo; end
  end
end
```

Current RBI:
```ruby
class Foo
  class << self
    def foo; end
  end
end
```

Expected RBI:
```ruby
class Foo
  def initialize(*args, &blk); end

  class << self
    def foo; end
  end
end
```

**Comment by RyanBrushett** [comment]
I don't think this is a bug. The class will inherit `initialize` from Object since it hasn't defined one for itself. Along with a bunch of other methods. I think Tapioca is handling this appropriately.
