### ISSUE TITLE
Provide RBI generation for Protobuf

### ISSUE THREAD

**Issue by Morriar** [Shopify/tapioca#65]
Sorbet recently [dropped support for Protobuf](https://github.com/sorbet/sorbet/commit/f20d4ccac5c893c48cf3407b6f8af65aac9ff3ab) and recommend using https://github.com/coinbase/protoc-gen-rbi instead which is a Go tool.

I think we can support this feature in Tapioca.

**Comment by KaanOzkan** [comment]
Looks like the commit message on https://github.com/Shopify/shopify/commit/9eedbbd8179c79b95684be5e7929f990cd80e5dd was wrongly interpreted by Github as it "closes" this issue. Reopening this.

**Comment by paracycle** [comment]
I looked into this a little bit and it looks like this won't be so complicated to pull off. Here are my findings:

1. Protocol Buffers tooling converts `.proto` files to `.rb` files, which are then checked into our repo as the file: `lib/shopify/protobuf/cart.rb`.
2. The types that we want to generate RBIs for in here are the ones declared at the end of the file under the `Shopify::Protobuf` namespace.
3. Each of those types includes a module named `Google::Protobuf::MessageExts`. So we can grab all these types using: `ObjectSpace.each_object(Class).select { |c| c < Google::Protobuf::MessageExts && !c.singleton_class? }`
4. Now, each of these types have a class method named `descriptor` which returns an instance of `Google::Protobuf::Descriptor` which is an enumerable.
5. When enumerated, each item is an instance of `Google::Protobuf::FieldDescriptor`.
6. Each of those objects has methods for getting the:
  - Name of the field using the `name` method
  - Type of the field using the `type` method (and using the `subtype` method if the type is complex)

This should be enough to generate methods that exist at runtime on these Protocol Buffers types.

**Comment by paracycle** [comment]
An example session:
```ruby
pry> ObjectSpace.each_object(Class).select { |c| c < Google::Protobuf::MessageExts && !c.singleton_class? }.fifth.tap { |c| puts c.name }.descriptor.each { |f| puts "#{f.name}: #{f.type} #{f.subtype.try(:enummodule) || f.subtype.try(:msgclass)}" }
Shopify::Protobuf::DiscountApplication
key: string
title: string
description: string
value: message Google::Protobuf::DoubleValue
created_at: message Google::Protobuf::Timestamp
type: string
value_type: enum Shopify::Protobuf::VALUE_TYPE
allocation_method: enum Shopify::Protobuf::DiscountApplication::ALLOCATION_METHOD
target_selection: enum Shopify::Protobuf::DiscountApplication::TARGET_SELECTION
target_type: enum Shopify::Protobuf::DiscountApplication::TARGET_TYPE
```
