### ISSUE TITLE
Tapioca gem command should not consider optional dependencies

### ISSUE THREAD

**Issue by Morriar** [Shopify/tapioca#655]
For example when generating RBIs for a project including [`reline`](https://github.com/ruby/reline):

```rb
# Gemfile

source 'https://rubygems.org'

gem "reline"
gem "tapioca", require: false
```

Since `reline` has an [optional dependency](https://github.com/ruby/reline/blob/master/lib/reline/terminfo.rb#L1-L10) to `fiddle`, running `tapioca gem` will produce the following RBI:

```rbi
# sorbet/rbi/gems/reline@0.2.7.rbi

...
module Reline::Terminfo
  extend ::Fiddle
  extend ::Fiddle::CParser
  extend ::Fiddle::Importer

  ...
end
```

Which will create a type error since `CParser` and `Importer` are not defined anywhere:

```
$ bundle exec srb tc

sorbet/rbi/gems/reline@0.2.7.rbi:608: Unable to resolve constant CParser
sorbet/rbi/gems/reline@0.2.7.rbi:609: Unable to resolve constant Importer
```

The current workaround is to define those constants in a shim RBI (or to run `tapioca todo`:

```rbi
# sorbet/rbi/shims/reline.rbi

module Fiddle::CParser; end
module Fiddle::Importer; end
```

But maybe Tapioca should be smart enough to not generate references to these constants since they're not loaded?

**Comment by paracycle** [comment]
Is this still an issue on `main`? I think this is again due to autoloading and not because the gem was an optional dependency, so this should be fixed on the `main` branch.

More generally, there is no way for Tapioca to know how `fiddle` is used as a dependency inside `reline`. If `reline` ends up trying to load `fiddle` and `fiddle` is a part of the application's `Gemfile`, then the load will happen (as it has in this case) and these mixins will be defined.

**Comment by Morriar** [comment]
I just tested again with Tapioca's main and it is still an issue.

**Comment by Morriar** [comment]
You don't see the errors because I fixed the payload RBIs upstream: https://github.com/sorbet/sorbet/pull/5903.

The main problem here is that we do generate those `extends`. Even if it doesn't produce type checking errors anymore in this case that doesn't mean that another gem wouldn't produce errors for other constants.

> 1. How are files loaded during srb tc?

1. It has an internal set of RBIs called "payload": https://github.com/sorbet/sorbet/tree/master/rbi
2. Then it will load all the files pointed by the `--dir` in the Sorbet config ([example](https://github.com/Shopify/tapioca/blob/main/sorbet/config#L1-L2)) the load order is not determinist.

> 2. Does it always go through all rbi files when type checking?

Yes.

**Comment by st0012** [comment]
What I try to say is, the `extend`s generated seems legit to me because if you load `reline` in CRuby, `fiddle` is not optional and will be loaded as well.

```
$ ruby -e "require 'reline'; puts Reline::Terminfo.singleton_class.ancestors"
#<Class:Reline::Terminfo>
Fiddle::Importer
Fiddle::CParser
Fiddle
Module
Object
Kernel
BasicObject
```

So this is not true, they should be generated:

> But maybe Tapioca should be smart enough to not generate references to these constants since they're not loaded?

The question should be, why aren't they loaded during type checking?
