### ISSUE TITLE
Verify fails because aasm gem RBIs added in different places

### ISSUE THREAD

**Issue by bmulholland** [Shopify/tapioca#656]
My CI generates the RBI for a model I use with `aasm` in a slightly different way, and so the `--verify` command fails. The same result is produced, but on different lines. Specifically, the following is just moved lower down (this is a git diff from logging in and running a dsl check myself):

```
-  class << self
-    sig { params(args: T.untyped, block: T.nilable(T.proc.bind(PrivateAASMMachine).void)).returns(PrivateAASMMachine)
}
-    def aasm(*args, &block); end
-  end
-
-  STATE_STARTED = T.let(T.unsafe(nil), Symbol)
-  STATE_FINISHED = T.let(T.unsafe(nil), Symbol)
-
-  class PrivateAASMMachine < AASM::Base
# etc
# Later
+  class PrivateAASMMachine < AASM::Base
# etc
+  STATE_FINISHED = T.let(T.unsafe(nil), Symbol)
   STATE_READY = T.let(T.unsafe(nil), Symbol)
+  STATE_STARTED = T.let(T.unsafe(nil), Symbol)
+
+  class << self
+    sig { params(args: T.untyped, block: T.nilable(T.proc.bind(PrivateAASMMachine).void)).returns(PrivateAASMMachine) }
+    def aasm(*args, &block); end
+  end
```
(etc)

**Comment by Morriar** [comment]
I believe this has been fixed since https://github.com/Shopify/tapioca/pull/630 (and more precisely https://github.com/Shopify/rbi/pull/106) have been merged.

Can you try with a more recent Tapioca please? 🙏 

I'll close this, feel free to reopen if the bug occurs on Tapioca latest version.

**Comment by bmulholland** [comment]
Thanks, confirmed that works
