### ISSUE TITLE
Method add_column does not exist on SomeMigrationName

### ISSUE THREAD

**Issue by nfm** [Shopify/tapioca#696]
I'm a new user of sorbet and tapioca so please forgive me if I've done something silly here.

I've set up sorbet on my Rails project (`bundle exec srb init`), which marked many of my migrations as `# typed: true`. Here's an example migration for context:

```ruby
# typed: true
class SomeMigrationName < ActiveRecord::Migration[6.1]
  def change
    add_column :some_table, :some_column, :text
  end
end
```

At this point, running `bundle exec srb tc` passes.

When I add tapioca (following along with the instructions in the [migration guide](https://github.com/Shopify/tapioca/wiki/Migrating-to-Tapioca#run-tapioca-dsl)), I've removed the entire `sorbet/rbi` folder, initialized tapioca (`bundle exec tapioca init`) and generated RBIs for all my gems (`bin/tapioca gem --all`).

Now when I run `bundle exec srb tc`, I get several type errors relating to ActiveRecord migrations, of the form `Method add_column does not exist on SomeMigrationName`. These present for `add_column`, `add_index`, `remove_column`, `remove_index`, `add_foreign_key`, `change_column_null`, and other core ActiveRecord migration methods.

If I go back and checkout my commit where I initialized sorbet (before removing `sorbet/rbi`), it looks like it's sourcing the type definitions for eg. `add_column` from `sorbet/rbi/sorbet-typed/lib/activerecord/~>6.1.0.rc1/activerecord.rbi`.

At the commit where I generate RBIs for gems using tapioca, when I grep `sorbet/rbi` for `add_column`, there _are_ a number of matches in `sorbet/rbi/gems/activerecord@6.1.4.4.rbi`, but these method definitions don't appear to match (or be used by sorbet - not sure which):

```sh
2069:  def add_column(name, type, **options); end
2957:  def add_column_options!(sql, options); end
2978:  def add_column(table_name, column_name, type, **options); end
3030:  def add_column_for_alter(table_name, column_name, type, **options); end
3456:  def add_column_options!(sql, options); end
3518:  def add_column(table_name, column_name, type, **options); end
3519:  def add_columns(table_name, *column_names, type:, **options); end
3582:  def add_column_for_alter(table_name, column_name, type, **options); end
5057:  def add_column(*args, &block); end
5125:  def invert_add_column(args, &block); end
5172:  def add_column(table_name, column_name, type, **options); end
```

Should the RBI file tapioca has generated produce interfaces that will satisfy `srb tc` in the same way the `sorbet-typed` file does? My understanding from the migration guide was that it would.

Thanks for the help, excited to start using tapioca and friends 🤙

**Comment by nfm** [comment]
Thanks @KaanOzkan, that's super helpful 🙏 Good context to know that Shopify currently has `typed: false` on Rails migrations.

For anyone else that comes across this issue, my current workaround was to add the `sorbet-typed` RBIs back in for `ActiveRecord` (rather than ignoring `db/migrate`).

I'm hoping we can start using tapioca and sorbet in our production codebase, and if we do I may be able to start contributing to the ecosystem 😁

**Comment by bjacobso** [comment]
I'm new to sorbet and tapioca, but I think I got this working with a custom dsl compiler:

```ruby
# typed: true
# frozen_string_literal: true

module Tapioca
  module Compilers
    class ActiveRecord < Tapioca::Dsl::Compiler
      extend T::Sig

      ConstantType = type_member { { fixed: T.class_of(::ActiveRecord::Migration) } }

      sig { override.returns(T::Enumerable[Class]) }
      def self.gather_constants
        all_classes.select { |c| c < ::ActiveRecord::Migration }
      end

      sig { override.void }
      def decorate
        root.create_path(constant) do |klass|
          klass.create_include('ActiveRecord::ConnectionAdapters::SchemaStatements')
        end
      end
    end
  end
end
```
