### ISSUE TITLE
typed_overrides are not working

### ISSUE THREAD

**Issue by atanbt** [Shopify/tapioca#711]
I'm having the same issue as #564 except there seems to be no way to resolve the issue I'm seeing.

Versions:

```
    devise (4.8.1)
    tapioca (0.6.1)
    sorbet (0.5.9528)
```

I'm setting

```
typed_overrides:
  "devise": "ignore"
```

Then I run `bundle exec tapioca gem` or `bundle exec tapioca devise` but the rbi always generated with typed: true at the top for some reason, which is odd because this config works for other gems.

I've also tried setting it to false but that hasn't worked either.

Here's the output:

```
alextan@Alex-BT ~/C/web (rails-6-1)> be tapioca gem devise
Requiring all gems to prepare for compiling... **************************************************
⛔️ WARNING: Sidekiq testing API enabled, but this is not the test environment.  Your jobs will not go to Redis.
**************************************************
 Done

Removing RBI files of gems that have been removed:

  Nothing to do.

DEPRECATION WARNING: [Devise] including `Devise::TestHelpers` is deprecated and will be removed from Devise.
For controller tests, please include `Devise::Test::ControllerHelpers` instead.
 (called from load at /Users/alextan/.rbenv/versions/2.7.5/bin/tapioca:23)
  Compiled devise
   identical  sorbet/rbi/gems/devise@4.8.1.rbi

All operations performed in working directory.
Please review changes and commit them.
```

**Comment by KaanOzkan** [comment]
You are probably using a new version of tapioca. Can you try adding a top level key called `gem` and try again: https://github.com/Shopify/tapioca#configuration

**Comment by atanbt** [comment]
@KaanOzkan looks like that did the trick. Thanks!

**Comment by paracycle** [comment]
As an additional point, instead of setting the strictness level of the generated Device gem RBI to `ignore`, you can also `exclude` the gem completely.
