### ISSUE TITLE
Gem RBI generation does not generate `sig(:final)` methods as final

### ISSUE THREAD

**Issue by azodpey** [Shopify/tapioca#766]

**Comment by paracycle** [comment]
@azodpey can you please send a reproduction example? Without that, we have no idea where to look.

**Comment by azodpey** [comment]
@paracycle Below are the steps:
- Add a class of something like below in you repository:
```
module ABC
  class XYZ
    extend T::Sig
    extend T::Helpers
    
    final!

    sig(:final) do
      params(
        configuration: T.nilable(String),
      ).
      void
    end
    def initialize(configuration: nil)
      configuration = T.let(configuration || "test", String)
      @config = T.let(configuration, String)
    end
```
- Release and package your repository, to be used as a gem say "gem-1".
- Bundle install this gem in your other respository and run `tapioca gem gem-1`

Expected: The RBI file which is generated should mark the class XYZ and its methods as final
Actual: The RBI file which is generated does not mark the class XYZ and its methods as final

Impact: When you run `srb tc` on your repository, it will give below error:
```
ABC::XYZ was declared as final but its method initialize was not declared as final
```

**Comment by paracycle** [comment]
We don't need to run code packaged in gems, we have isolated test cases for all constructs that Tapioca should support.

So, this should be enough for a test case, right?
```ruby
module Foo
  extend T::Sig
  extend T::Helpers

  final!

  sig(:final) { void }
  def foo
  end
end
```

When I run that in a test, I see that we are generating the `final!` on the class but not on the method `foo`. That also matches the error you are seeing.

**Comment by azodpey** [comment]
Yup, that's the exact thing I observed: `we are generating the final! on the class but not on the method foo`
