### ISSUE TITLE
Handle inclusions of `T::Props::Plugin`

### ISSUE THREAD

**Issue by Morriar** [Shopify/tapioca#78]
The following code in a gem:

```ruby
module Foo
  include T::Props::Constructor
  extend T::Helpers

  module Bar
    include T::Props::ClassMethods
  end

  mixes_in_class_methods Bar
end
```

Will produce the following RBI with `tapioca`:

```ruby
module Foo
  mixes_in_class_methods(::T::Props::Plugin::ClassMethods)
end

module Foo::Bar
end
```

Because `T::Props::Constructor` includes `T::Props::Plugin` which already does:

```ruby
mixes_in_class_methods(T::Props::Plugin::ClassMethods)
```

**Comment by katayounHillier** [comment]
Using the sorbet sandbox:

module Foo::Bar
    mixes_in_class_methods(::T::Props::Plugin:ClassMethods)
end
 Will generate  the following error :

editor.rb:5: Argument to mixes_in_class_methods must be statically resolvable to a module https://srb.help/5020
     5 |    mixes_in_class_methods(::T::Props::Plugin:ClassMethods)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
 
So if we fix the issue that we addressed in this bug, there is still sorbet issue , the generated code should be :

module Foo::Bar
    mixes_in_class_methods(::T::Props::ClassMethods)
end
