### ISSUE TITLE
Invalid type_member inserted into RBI file

### ISSUE THREAD

**Issue by kbacha** [Shopify/tapioca#838]
We noticed that tapioca is not properly replicating generics within generic type_members. In one of our gems we have a generic like this:

```ruby
InputType = type_member(fixed: Input)
ReturnType = type_member(fixed: Result[OkType, ErrType])
```

in the rbi file generated for this type in a gem which depends on it, the output is:

```ruby
InputType = type_member(fixed: Input)
ReturnType = type_member(fixed: #<Class:0x00007fb9d58fdce8>)
```

It appears to be placing an anonymous class string in the position of the generic type instead of it's actual type.

**Comment by paracycle** [comment]
Ok, I can recreate this and I think I have a fix for it already. I'll PR it soon.
