### ISSUE TITLE
Improper loading of Rails engines 

### ISSUE THREAD

**Issue by wildmaples** [Shopify/tapioca#993]
# Issue 

When `tapioca gems` command is run, rails engines are loaded in the [`Tapioca::Runtime::Loader#load_rails_engines` method](https://github.com/Shopify/tapioca/blob/main/lib/tapioca/runtime/loader.rb#L103), where engines are sorted then required/loaded. 

Any [`LoadError` exceptions are rescued](https://github.com/Shopify/tapioca/blob/main/lib/tapioca/runtime/loader.rb#L110-L112) and files are saved to be [reloaded again](https://github.com/Shopify/tapioca/blob/main/lib/tapioca/runtime/loader.rb#L115-L121). 

This causes issues because if the files are loaded incorrectly both times, they are never loaded. This cascades down to `uninitialized constant (NameError)` later when the unloaded constants are called, which is something we're currently seeing on Shopify/shopify.  

# Questions
- Why are files from the engine being sorted and loaded this way? Is there an assumption that there is autoload in place? I don't think sorting and loading them is the correct way to do it. The arbitrary loading order seems to be the root of this issue. 
- Do we need to load files from rails engines? Rails engines are listed in the Gemfile but they are part of the Rails application so it seems like they are in the gray area of whether or not Tapioca is responsible for them.

**Comment by paracycle** [comment]
> Not all engines. The Active Storage engine is not part of the Rails application, or the devise engine. I think we don't need to load engines that are inside the application directory though.

Yes, this is the correct fix, which I was going to suggest as well.

**Comment by paracycle** [comment]
Btw, it is also true that our Rails engine loading code is very hacky and does not work well. There is even an issue #671 that tracks that generally. But, it is still worthwhile to exclude any application engines from the loading process.

**Comment by KaanOzkan** [comment]
https://github.com/Shopify/tapioca/pull/995
