### ISSUE TITLE
Protobuf DSL blocks gem install

### ISSUE THREAD

**Issue by bmulholland** [Shopify/tapioca#998]
I'm trying to install a gem which depends on google-protobuf; when I do, tapioca's DSL compiler causes sorbet errors. I tried to ignore the classes in my tapioca config, but those weren't respected. So I'm blocked from installing the gem entirely.

tapioca 0.8.1

Tapioca config I tried:
```
dsl:
  exclude:
    - Google::Protobuf
    - Google::Protobuf::FileOptions
    - Google::Protobuf::FieldDescriptorProto
    - Google::Protobuf::MethodOptions
```

Some excerpts of Sorbet errors:

```
sorbet/rbi/dsl/google/protobuf/file_options.rbi:113: Unable to resolve constant OptimizeMode https://srb.help/5002
     113 |    ).returns(Google::Protobuf::FileOptions::OptimizeMode)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

sorbet/rbi/dsl/google/protobuf/field_descriptor_proto.rbi:13: Unable to resolve constant Label https://srb.help/5002
    13 |      label: Google::Protobuf::FieldDescriptorProto::Label,

sorbet/rbi/dsl/google/protobuf/field_descriptor_proto.rbi:19: Unable to resolve constant Type https://srb.help/5002
    19 |      type: Google::Protobuf::FieldDescriptorProto::Type,

sorbet/rbi/dsl/google/protobuf/field_options.rbi:10: Unable to resolve constant CType https://srb.help/5002
    10 |      ctype: Google::Protobuf::FieldOptions::CType,
```

**Comment by thomasdziedzic-census** [comment]
This is what I have in my `sorbet/tapioca/config.yml`:

```yaml
---
gem:
  typed_overrides:
    'google-protobuf': 'false'
```

**Comment by bmulholland** [comment]
That would override the RBIs for the gem, but these errors come from the generated DSL so that workaround doesn't work.

**Comment by KaanOzkan** [comment]
@bmulholland  DSLs are generated by loading the application which in turn can load more of the gem than `tapioca gem` command does. As a result sometimes it might refer to constants that weren't available during gem RBI generation.

In this case `google-protobuf` gem doesn't seem to be loading enough constants by default. I believe adding `require "google/protobuf"` in your `sorbet/tapioca/require.rb` should manually load the gem and give you those constants.

If not you can look for another file to require and even write shims to define unknown constants manually.
